// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as protocol$0 from "../../../../sushidev-team/lola/internal/protocol/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "daemon:alive": boolean;
            "daemon:projects": protocol$0.ProjectsData;
            "daemon:sessions": protocol$0.SessionsData;
            "daemon:status": protocol$0.StatusData;
        }
    }
}
