// Package hook is the callback path from a Claude Code hook process into the
// lola daemon. The launcher exports LOLA_SESSION in the agent's tmux pane and
// starts claude with `--settings <file>` generated by SettingsJSON, which
// wires the four lifecycle hooks to `lola hook <event>`. That subcommand
// calls Post, which reports the event over the daemon socket as a
// protocol.Request{Cmd: "hookEvent"}.
//
// Everything here is on the agent's critical path: Post is bounded by a 2s
// total deadline and any failure returns immediately — a dead daemon must
// never wedge or fail an agent's turn (the caller additionally always exits
// 0).
package hook

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/sushidev-team/lola/internal/config"
	"github.com/sushidev-team/lola/internal/protocol"
)

// postTimeout caps the entire Post call: dial + write + best-effort read.
var postTimeout = 2 * time.Second

// Post reports one normalized hook event ("stop", "notification",
// "session_end", "tool_use", "user_prompt") for the session named by
// $LOLA_SESSION to the daemon socket at config.Home()/lola.sock, carrying the
// structured payload fields the CLI extracted (protocol.HookPayload; a zero
// payload is omitted from the wire). It sends a single protocol.Request line
// and reads the single response line best-effort — a missing or slow reply is
// not an error once the request is on the wire.
func Post(event string, p protocol.HookPayload) error {
	session := os.Getenv("LOLA_SESSION")
	if session == "" {
		return errors.New("not a lola session ($LOLA_SESSION unset)")
	}
	home, err := config.Home()
	if err != nil {
		return err
	}

	deadline := time.Now().Add(postTimeout)
	d := net.Dialer{Deadline: deadline}
	conn, err := d.Dial("unix", filepath.Join(home, "lola.sock"))
	if err != nil {
		return fmt.Errorf("dial lola daemon: %w", err)
	}
	defer conn.Close()
	_ = conn.SetDeadline(deadline)

	req := protocol.Request{
		Cmd:     "hookEvent",
		Session: session,
		Event:   event,
		Detail:  p.Reason, // the legacy short-reason field, kept for log lines
	}
	if p != (protocol.HookPayload{}) {
		req.Hook = &p
	}
	raw, err := json.Marshal(req)
	if err != nil {
		return err
	}
	if _, err := conn.Write(append(raw, '\n')); err != nil {
		return fmt.Errorf("send hook event: %w", err)
	}
	// Best-effort read of the daemon's one response line. Errors (timeout,
	// daemon closed without replying) are ignored: the event was written.
	_, _ = bufio.NewReader(conn).ReadString('\n')
	return nil
}

// ErrNoDaemon wraps every failure to REACH the daemon from Report (no session
// env, no socket, a timeout) as opposed to the daemon answering "no". The CLI
// treats the two differently: an unreachable daemon must not fail an agent's
// command — a report is never worth derailing a turn over — while a rejected
// report is shown so the agent can correct its call.
var ErrNoDaemon = errors.New("lola daemon unreachable")

// Report sends one `lola report` argv for the session named by $LOLA_SESSION
// (cmd=agentReport) and waits — within the same postTimeout bound as Post — for
// the daemon's verdict. Validation happens daemon-side (internal/board), so a
// non-nil error that is not ErrNoDaemon is the daemon's own usage message.
func Report(argv []string) error {
	session := os.Getenv("LOLA_SESSION")
	if session == "" {
		return fmt.Errorf("%w: not a lola session ($LOLA_SESSION unset)", ErrNoDaemon)
	}
	home, err := config.Home()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	args, err := json.Marshal(protocol.ReportArgs{Argv: argv})
	if err != nil {
		return err
	}
	raw, err := json.Marshal(protocol.Request{Cmd: "agentReport", Session: session, Args: args})
	if err != nil {
		return err
	}
	deadline := time.Now().Add(postTimeout)
	d := net.Dialer{Deadline: deadline}
	conn, err := d.Dial("unix", filepath.Join(home, "lola.sock"))
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	defer conn.Close()
	_ = conn.SetDeadline(deadline)
	if _, err := conn.Write(append(raw, '\n')); err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	line, err := bufio.NewReader(conn).ReadString('\n')
	if err != nil {
		return fmt.Errorf("%w: no reply: %v", ErrNoDaemon, err)
	}
	var resp protocol.Response
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return fmt.Errorf("%w: bad reply: %v", ErrNoDaemon, err)
	}
	if !resp.OK {
		// A daemon predating the command answers `unknown cmd`; that is the
		// same "nobody to report to" as a dead socket, not the agent's fault.
		if strings.HasPrefix(resp.Error, "unknown cmd") {
			return fmt.Errorf("%w: %s", ErrNoDaemon, resp.Error)
		}
		return errors.New(resp.Error)
	}
	return nil
}

// request sends one request for the session named by $LOLA_SESSION and decodes
// the daemon's reply into out (nil to ignore data), bounded by postTimeout.
// Unreachable-daemon failures wrap ErrNoDaemon, exactly like Report.
func request(cmd string, args any, out any) error {
	session := os.Getenv("LOLA_SESSION")
	if session == "" {
		return fmt.Errorf("%w: not a lola session ($LOLA_SESSION unset)", ErrNoDaemon)
	}
	home, err := config.Home()
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	req := protocol.Request{Cmd: cmd, Session: session}
	if args != nil {
		raw, err := json.Marshal(args)
		if err != nil {
			return err
		}
		req.Args = raw
	}
	raw, err := json.Marshal(req)
	if err != nil {
		return err
	}
	deadline := time.Now().Add(postTimeout)
	d := net.Dialer{Deadline: deadline}
	conn, err := d.Dial("unix", filepath.Join(home, "lola.sock"))
	if err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	defer conn.Close()
	_ = conn.SetDeadline(deadline)
	if _, err := conn.Write(append(raw, '\n')); err != nil {
		return fmt.Errorf("%w: %v", ErrNoDaemon, err)
	}
	line, err := bufio.NewReader(conn).ReadString('\n')
	if err != nil {
		return fmt.Errorf("%w: no reply: %v", ErrNoDaemon, err)
	}
	var resp protocol.Response
	if err := json.Unmarshal([]byte(line), &resp); err != nil {
		return fmt.Errorf("%w: bad reply: %v", ErrNoDaemon, err)
	}
	if !resp.OK {
		if strings.HasPrefix(resp.Error, "unknown cmd") {
			return fmt.Errorf("%w: %s", ErrNoDaemon, resp.Error)
		}
		return errors.New(resp.Error)
	}
	if out != nil && len(resp.Data) > 0 {
		return json.Unmarshal(resp.Data, out)
	}
	return nil
}

// SubmitPlan hands the agent's plan to the daemon (cmd=planSubmit).
func SubmitPlan(plan string) error {
	return request("planSubmit", protocol.PlanSubmitArgs{Plan: plan}, nil)
}

// PlanGate asks whether this session may edit files (cmd=planGate). Any
// failure to reach the daemon returns an ErrNoDaemon-wrapped error, and the
// caller then ALLOWS the edit: the hook must never wedge a turn on a dead lola.
func PlanGate() (protocol.PlanGateData, error) {
	var d protocol.PlanGateData
	err := request("planGate", nil, &d)
	return d, err
}

// PreToolUseDeny is the Claude Code PreToolUse hook output that denies the
// tool call and tells the model why.
func PreToolUseDeny(reason string) []byte {
	out, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":            "PreToolUse",
			"permissionDecision":       "deny",
			"permissionDecisionReason": reason,
		},
	})
	return append(out, '\n')
}

// planGatedTools are the claude tools the plan gate blocks: every file-WRITING
// tool. Bash is deliberately not in the list (it is how the agent investigates
// and submits the plan); the briefing forbids writing through it.
const planGatedTools = "Edit|Write|MultiEdit|NotebookEdit"

// Claude Code settings shapes for SettingsJSON. Struct (not map) so the JSON
// key order is deterministic and golden-testable.
type hookSpec struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
	Async   bool   `json:"async,omitempty"`
}

type matcherEntry struct {
	Matcher string     `json:"matcher"`
	Hooks   []hookSpec `json:"hooks"`
}

type settingsFile struct {
	Hooks struct {
		Stop             []matcherEntry `json:"Stop"`
		Notification     []matcherEntry `json:"Notification"`
		SessionEnd       []matcherEntry `json:"SessionEnd"`
		PostToolUse      []matcherEntry `json:"PostToolUse"`
		UserPromptSubmit []matcherEntry `json:"UserPromptSubmit"`
		PreToolUse       []matcherEntry `json:"PreToolUse"`
	} `json:"hooks"`
	SkillOverrides map[string]string `json:"skillOverrides,omitempty"`
	StatusLine     *statusLineSpec   `json:"statusLine,omitempty"`
}

type statusLineSpec struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

// modalSkills are the Claude Code skills that interrupt a session with a MODAL
// dialog nobody is sitting in front of. SettingsJSON turns each off ("off" is
// claude-code's own skillOverrides vocabulary, alongside "on", "name-only" and
// "user-invocable-only"), because a lola worker runs unattended: an overlay
// waiting on a keypress wedges the session for as long as it is up, holds a
// concurrency slot, and — the reason this list exists — SWALLOWS anything the
// daemon types at the pane.
//
// `auto-mode-setup` is the "Set up auto mode for your environment?" wizard. It
// is offered only to sessions already in auto permission mode, which is every
// lola worker, and it appears AFTER a turn ends — i.e. right where the Stop hook
// has just opened the send-keys gate. Four review hand-offs were typed into it
// and lost before the pane check in handoffPromptProof was tightened.
//
// The overrides are the PREVENTION half; they are not the safety net. Claude
// Code adds dialogs faster than this list can track them, so attention.Classify
// still fails closed on any modal it sees (ActivityBlocked) — keep both.
var modalSkills = map[string]string{
	"auto-mode-setup": "off",
}

// SettingsJSON generates the content of the per-session Claude Code settings
// file (passed as `claude --settings <file>`, so the project's own settings
// stay untouched) wiring the lifecycle hooks to lolaBin:
//
//	Stop             → <lolaBin> hook stop
//	Notification     → <lolaBin> hook notification
//	SessionEnd       → <lolaBin> hook session_end
//	PostToolUse      → <lolaBin> hook tool_use     (async: the liveness heartbeat
//	                                                never wakes or blocks the agent)
//	PreToolUse       → <lolaBin> hook pre_tool_use (file-edit tools only: the
//	                                                plan-approval gate's deny)
//	UserPromptSubmit → <lolaBin> hook user_prompt  (turn START: clears the
//	                                                AtPrompt send-keys gate so a
//	                                                human-initiated attach turn —
//	                                                which fires no PostToolUse for
//	                                                a text-only reply — is never
//	                                                seen as idle mid-turn)
//
// Each hook has an explicit 10s timeout. Hook commands run with the pane's
// environment, so the exported LOLA_SESSION is visible to `lola hook`.
//
// The status line is `<lolaBin> hook statusline` (statusline.go): the only
// place Claude Code hands out the subscription limits, recorded for the
// app/TUI header and then passed through to the user's own status-line
// command, so the pane looks unchanged.
//
// It also carries the modalSkills overrides, which suppress the interactive
// dialogs an unattended worker can never answer. `--settings` lands in Claude
// Code's flagSettings source, which is always merged, so the overrides apply
// without touching the user's own settings.
func SettingsJSON(lolaBin string) []byte {
	bin := shQuote(lolaBin)
	entry := func(event string, async bool) []matcherEntry {
		return []matcherEntry{{
			Matcher: "",
			Hooks: []hookSpec{{
				Type:    "command",
				Command: bin + " hook " + event,
				Timeout: 10,
				Async:   async,
			}},
		}}
	}

	var s settingsFile
	s.Hooks.Stop = entry("stop", false)
	s.Hooks.Notification = entry("notification", false)
	s.Hooks.SessionEnd = entry("session_end", false)
	s.Hooks.PostToolUse = entry("tool_use", true)
	// Synchronous (not async): AtPrompt must be reliably cleared at turn start,
	// before the agent produces any output the reaction engine might race.
	s.Hooks.UserPromptSubmit = entry("user_prompt", false)
	// The plan-approval gate: synchronous, because its stdout DECIDES the tool
	// call. Wired into every session (an ungated one is answered "allowed" in
	// one socket round trip) so the gate needs no per-project settings variant.
	s.Hooks.PreToolUse = []matcherEntry{{
		Matcher: planGatedTools,
		Hooks: []hookSpec{{
			Type:    "command",
			Command: bin + " hook pre_tool_use",
			Timeout: 10,
		}},
	}}
	s.SkillOverrides = modalSkills
	s.StatusLine = &statusLineSpec{Type: "command", Command: bin + " " + statusLineSelf}

	out, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		panic(err) // static shape; cannot fail
	}
	return append(out, '\n')
}

// safeBin matches paths that need no shell quoting.
var safeBin = regexp.MustCompile(`^[A-Za-z0-9_%+=:,./@-]+$`)

// shQuote single-quotes s for the shell that runs hook commands, unless it is
// already shell-safe (the common /path/to/lola case, kept unquoted so the
// generated settings stay readable).
func shQuote(s string) string {
	if s != "" && safeBin.MatchString(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
