// Package hook is the callback path from a Claude Code hook process into the
// lola daemon. The launcher exports LOLA_SESSION in the agent's tmux pane and
// starts claude with `--settings <file>` generated by SettingsJSON, which
// wires the four lifecycle hooks to `lola hook <event>`. That subcommand
// calls Post, which reports the event over the daemon socket as a
// protocol.Request{Cmd: "hookEvent"}.
//
// Everything here is on the agent's critical path: Post is bounded by a 2s
// total deadline and any failure returns immediately — a dead daemon must
// never wedge or fail an agent's turn (the caller additionally always exits
// 0).
package hook

import (
	"bufio"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/sushidev-team/lola/internal/config"
	"github.com/sushidev-team/lola/internal/protocol"
)

// postTimeout caps the entire Post call: dial + write + best-effort read.
var postTimeout = 2 * time.Second

// Post reports one normalized hook event ("stop", "notification",
// "session_end", "tool_use") for the session named by $LOLA_SESSION to the
// daemon socket at config.Home()/lola.sock. It sends a single
// protocol.Request line and reads the single response line best-effort — a
// missing or slow reply is not an error once the request is on the wire.
func Post(event, detail string) error {
	session := os.Getenv("LOLA_SESSION")
	if session == "" {
		return errors.New("not a lola session ($LOLA_SESSION unset)")
	}
	home, err := config.Home()
	if err != nil {
		return err
	}

	deadline := time.Now().Add(postTimeout)
	d := net.Dialer{Deadline: deadline}
	conn, err := d.Dial("unix", filepath.Join(home, "lola.sock"))
	if err != nil {
		return fmt.Errorf("dial lola daemon: %w", err)
	}
	defer conn.Close()
	_ = conn.SetDeadline(deadline)

	raw, err := json.Marshal(protocol.Request{
		Cmd:     "hookEvent",
		Session: session,
		Event:   event,
		Detail:  detail,
	})
	if err != nil {
		return err
	}
	if _, err := conn.Write(append(raw, '\n')); err != nil {
		return fmt.Errorf("send hook event: %w", err)
	}
	// Best-effort read of the daemon's one response line. Errors (timeout,
	// daemon closed without replying) are ignored: the event was written.
	_, _ = bufio.NewReader(conn).ReadString('\n')
	return nil
}

// Claude Code settings shapes for SettingsJSON. Struct (not map) so the JSON
// key order is deterministic and golden-testable.
type hookSpec struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
	Async   bool   `json:"async,omitempty"`
}

type matcherEntry struct {
	Matcher string     `json:"matcher"`
	Hooks   []hookSpec `json:"hooks"`
}

type settingsFile struct {
	Hooks struct {
		Stop         []matcherEntry `json:"Stop"`
		Notification []matcherEntry `json:"Notification"`
		SessionEnd   []matcherEntry `json:"SessionEnd"`
		PostToolUse  []matcherEntry `json:"PostToolUse"`
	} `json:"hooks"`
}

// SettingsJSON generates the content of the per-session Claude Code settings
// file (passed as `claude --settings <file>`, so the project's own settings
// stay untouched) wiring the four lifecycle hooks to lolaBin:
//
//	Stop         → <lolaBin> hook stop
//	Notification → <lolaBin> hook notification
//	SessionEnd   → <lolaBin> hook session_end
//	PostToolUse  → <lolaBin> hook tool_use   (async: the liveness heartbeat
//	                                          never wakes or blocks the agent)
//
// Each hook has an explicit 10s timeout. Hook commands run with the pane's
// environment, so the exported LOLA_SESSION is visible to `lola hook`.
func SettingsJSON(lolaBin string) []byte {
	bin := shQuote(lolaBin)
	entry := func(event string, async bool) []matcherEntry {
		return []matcherEntry{{
			Matcher: "",
			Hooks: []hookSpec{{
				Type:    "command",
				Command: bin + " hook " + event,
				Timeout: 10,
				Async:   async,
			}},
		}}
	}

	var s settingsFile
	s.Hooks.Stop = entry("stop", false)
	s.Hooks.Notification = entry("notification", false)
	s.Hooks.SessionEnd = entry("session_end", false)
	s.Hooks.PostToolUse = entry("tool_use", true)

	out, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		panic(err) // static shape; cannot fail
	}
	return append(out, '\n')
}

// safeBin matches paths that need no shell quoting.
var safeBin = regexp.MustCompile(`^[A-Za-z0-9_%+=:,./@-]+$`)

// shQuote single-quotes s for the shell that runs hook commands, unless it is
// already shell-safe (the common /path/to/lola case, kept unquoted so the
// generated settings stay readable).
func shQuote(s string) string {
	if s != "" && safeBin.MatchString(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
