// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService lets the settings / project / poll forms read and write
 * config.toml directly, the same way the TUI does — the daemon protocol has no
 * config-write command; config.toml is the single source of truth and the
 * daemon only re-reads it on `reload`. Every Save validates, persists atomically
 * (config.Save is temp+rename, 0600), then best-effort reloads a live daemon.
 * 
 * Secrets never pass through here: the Linear key and Slack webhook live in the
 * keychain / env by *name*, and those name fields are the only secret-adjacent
 * values these DTOs carry.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Branches lists the branches the checkout at path can fork worktrees from —
 * local branches plus remote-tracking ones with no local counterpart, the
 * repository's own default first. Empty when path is not a checkout; the form
 * then leaves the field as free text rather than trapping the user.
 */
export function Branches(path: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3689606875, path);
}

/**
 * ConfigExists reports whether ~/.lola/config.toml is present, so the frontend
 * can gate a first-run setup screen.
 */
export function ConfigExists(): $CancellablePromise<boolean> {
    return $Call.ByID(1455498937);
}

/**
 * DetectRepo resolves the GitHub "owner/name" of the checkout at path so the
 * project form can prefill Repo instead of making the user copy it. Returns ""
 * when it cannot be determined — not a git repo, no GitHub remote, a
 * non-GitHub host. That empty value is deliberate and safe: it disables PR
 * checks (fail-closed) rather than pointing them at the wrong repository.
 * 
 * Prefers the "upstream" remote over "origin": in a fork, origin is the fork
 * but upstream is where the pull requests actually land.
 */
export function DetectRepo(path: string): $CancellablePromise<string> {
    return $Call.ByID(1658393536, path);
}

/**
 * GetProject returns the named project's full form state. An empty name is a
 * new project: it starts inheriting everything it can, so a first project picks
 * up whatever shared setup [defaults] already carries.
 */
export function GetProject(name: string): $CancellablePromise<$models.ProjectFormDTO> {
    return $Call.ByID(3485741446, name);
}

export function GetSettings(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(2761787168);
}

/**
 * GetTheme returns the EFFECTIVE theme identifier — never "" — so the frontend
 * has one unambiguous value to apply. A config that cannot be read falls back
 * to the default rather than erroring: a broken or missing config must still
 * paint.
 */
export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(243714106);
}

/**
 * MigrateReview folds the legacy [review]/[coderabbit] tables into the editable
 * provider catalog and persists (one-way; mirrors `lola config migrate-review`
 * and the TUI's in-place migrate). A no-op when there is nothing to migrate.
 */
export function MigrateReview(): $CancellablePromise<void> {
    return $Call.ByID(486961436);
}

/**
 * PrioritySortKeys returns the sort keys the daemon understands, so the
 * settings form can offer them instead of taking free text. These are LOLA's
 * own keys, not a Linear concept — there is nothing to fetch from the API.
 */
export function PrioritySortKeys(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3393829323);
}

export function RemoveProject(name: string): $CancellablePromise<void> {
    return $Call.ByID(581203932, name);
}

/**
 * ReviewProviderKinds / TransportTokens expose the selectable catalog values so
 * the frontend renders its pickers without hardcoding them.
 */
export function ReviewProviderKinds(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3055606205);
}

export function SaveProject(dto: $models.ProjectFormDTO): $CancellablePromise<void> {
    return $Call.ByID(3368157871, dto);
}

export function SaveSettings(dto: $models.SettingsDTO): $CancellablePromise<void> {
    return $Call.ByID(298700571, dto);
}

/**
 * SetTheme persists [ui].theme on its own. It writes through the shared
 * saveConfig path — Validate, then config.Save's atomic temp+rename, then a
 * best-effort daemon reload — so an unknown identifier is rejected here by the
 * same static check the daemon applies, and nothing writes the file directly.
 * An empty name clears the key, which drops the [ui] table and restores
 * config.DefaultUITheme.
 */
export function SetTheme(name: string): $CancellablePromise<void> {
    return $Call.ByID(1831643238, name);
}

/**
 * Setup writes the initial config.toml from the wizard: it stores the Linear key
 * in the Keychain (falling back to an env var by name if that fails), records one
 * project, and sets the caps/interval. The key itself is never written to config.
 */
export function Setup(dto: $models.SetupDTO): $CancellablePromise<$models.SetupResultDTO> {
    return $Call.ByID(3057086516, dto);
}

/**
 * Themes returns the theme identifiers config.Validate accepts, so the settings
 * form enumerates them instead of carrying its own copy that could drift out of
 * sync and start writing configs the daemon rejects. Same precedent as
 * PrioritySortKeys above.
 */
export function Themes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2762792109);
}

export function TransportTokens(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2864709098);
}

/**
 * ValidateLinearKey checks a key against Linear's API (Viewer), so the setup
 * screen can confirm it before writing config. Bounded to 15s.
 */
export function ValidateLinearKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(2105802151, key);
}
