// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService lets the settings / project / poll forms read and write
 * config.toml directly, the same way the TUI does — the daemon protocol has no
 * config-write command; config.toml is the single source of truth and the
 * daemon only re-reads it on `reload`. Every Save validates, persists atomically
 * (config.Save is temp+rename, 0600), then best-effort reloads a live daemon.
 * 
 * Secrets never pass through here: the Linear key and Slack webhook live in the
 * keychain / env by *name*, and those name fields are the only secret-adjacent
 * values these DTOs carry.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigExists reports whether ~/.lola/config.toml is present, so the frontend
 * can gate a first-run setup screen.
 */
export function ConfigExists(): $CancellablePromise<boolean> {
    return $Call.ByID(1455498937);
}

export function GetPoll(project: string): $CancellablePromise<$models.PollFormDTO> {
    return $Call.ByID(3340962240, project);
}

export function GetProject(name: string): $CancellablePromise<$models.ProjectFormDTO> {
    return $Call.ByID(3485741446, name);
}

export function GetSettings(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(2761787168);
}

export function RemoveProject(name: string): $CancellablePromise<void> {
    return $Call.ByID(581203932, name);
}

export function SavePoll(dto: $models.PollFormDTO): $CancellablePromise<void> {
    return $Call.ByID(2251699215, dto);
}

export function SaveProject(dto: $models.ProjectFormDTO): $CancellablePromise<void> {
    return $Call.ByID(3368157871, dto);
}

export function SaveSettings(dto: $models.SettingsDTO): $CancellablePromise<void> {
    return $Call.ByID(298700571, dto);
}

/**
 * Setup writes the initial config.toml from the wizard: it stores the Linear key
 * in the Keychain (falling back to an env var by name if that fails), records one
 * project, and sets the caps/interval. The key itself is never written to config.
 */
export function Setup(dto: $models.SetupDTO): $CancellablePromise<$models.SetupResultDTO> {
    return $Call.ByID(3057086516, dto);
}

/**
 * ValidateLinearKey checks a key against Linear's API (Viewer), so the setup
 * screen can confirm it before writing config. Bounded to 15s.
 */
export function ValidateLinearKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(2105802151, key);
}
