// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DaemonService is the Wails-bound bridge between the Svelte frontend and the
 * lola daemon. Every method is one socket round-trip (internal/protocol) and
 * returns the daemon's typed payload, which Wails emits as a TS model. It holds
 * no state beyond the resolved lola binary path used for lifecycle control.
 * 
 * Read commands (Sessions/Projects/Status) hit the daemon's in-memory caches and
 * are safe to poll frequently; the open* / pollOnce family do real work and use
 * the long timeout.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../internal/protocol/models.js";

/**
 * Alive reports whether the daemon socket accepts a connection right now.
 */
export function Alive(): $CancellablePromise<boolean> {
    return $Call.ByID(452437450);
}

/**
 * Answer types a human reply into a session parked at needs_input. The daemon
 * refuses it (returned as an error) unless the session is provably idle.
 */
export function Answer(session: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(3662326747, session, text);
}

/**
 * CodeRabbit forces the PR-comment watch for one session now.
 */
export function CodeRabbit(session: string): $CancellablePromise<protocol$0.CodeRabbitData> {
    return $Call.ByID(2376086832, session);
}

export function Disable(poll: string): $CancellablePromise<void> {
    return $Call.ByID(3917859687, poll);
}

/**
 * Enable turns a poll on. Disable turns it off.
 */
export function Enable(poll: string): $CancellablePromise<void> {
    return $Call.ByID(948893506, poll);
}

/**
 * Kill tears a session down. A dirty worktree is kept unless force is set.
 */
export function Kill(session: string, force: boolean): $CancellablePromise<protocol$0.KillData> {
    return $Call.ByID(699745421, session, force);
}

/**
 * Open checks out a branch or PR of a project into a throwaway shell worktree.
 */
export function Open(project: string, ref: string): $CancellablePromise<protocol$0.OpenData> {
    return $Call.ByID(580622853, project, ref);
}

/**
 * OpenManual starts a new branch off a base as an agent or a plain shell.
 */
export function OpenManual(a: protocol$0.OpenManualArgs): $CancellablePromise<protocol$0.OpenData> {
    return $Call.ByID(1277103427, a);
}

/**
 * OpenPR opens a PR head branch as a tracking worktree + agent (forks refused).
 */
export function OpenPR(a: protocol$0.OpenPrArgs): $CancellablePromise<protocol$0.OpenData> {
    return $Call.ByID(4194861095, a);
}

/**
 * OpenTicket starts a Linear issue on demand (deduped like a poll dispatch).
 */
export function OpenTicket(a: protocol$0.OpenTicketArgs): $CancellablePromise<protocol$0.OpenData> {
    return $Call.ByID(2410107461, a);
}

/**
 * OpenURL asks the daemon to open a URL in the default browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2744861822, url);
}

/**
 * PRs lists a project's open pull requests (short-TTL cache; refresh bypasses it).
 */
export function PRs(project: string, refresh: boolean): $CancellablePromise<protocol$0.PrsData> {
    return $Call.ByID(2669759928, project, refresh);
}

/**
 * Pane captures a session's tmux pane and runs the attention parser over it.
 * lines bounds the trailing rows captured (0 → the daemon default).
 */
export function Pane(session: string, lines: number): $CancellablePromise<protocol$0.PaneData> {
    return $Call.ByID(2291076911, session, lines);
}

/**
 * PollOnce runs one tick synchronously; dryRun performs zero side effects.
 */
export function PollOnce(poll: string, dryRun: boolean): $CancellablePromise<protocol$0.PollOnceData> {
    return $Call.ByID(3079472957, poll, dryRun);
}

/**
 * Projects returns the configured projects with live rollups.
 */
export function Projects(): $CancellablePromise<protocol$0.ProjectsData> {
    return $Call.ByID(2895050739);
}

/**
 * Reload asks the daemon to re-read config.toml and apply it live.
 */
export function Reload(): $CancellablePromise<void> {
    return $Call.ByID(2597423456);
}

/**
 * RenameProject changes a project's ID (not its display label — that is a plain
 * ConfigService.SaveProject field). The daemon owns this because the name keys
 * worktree dirs, the seen file and every tmux session name; it refuses while any
 * session still carries the old one.
 * 
 * It bypasses `call` deliberately: a refusal's payload carries the BLOCKING
 * session ids, and `call` drops Data on a non-OK response. Returning them lets
 * the form tell the human exactly what to finish rather than just "refused".
 */
export function RenameProject($from: string, to: string): $CancellablePromise<protocol$0.RenameProjectData> {
    return $Call.ByID(3384477348, $from, to);
}

/**
 * RestartDaemon stops (if up), waits for the socket to clear, then respawns.
 */
export function RestartDaemon(): $CancellablePromise<void> {
    return $Call.ByID(1780015196);
}

/**
 * Review forces a CodeRabbit QA pass for one session now.
 */
export function Review(session: string): $CancellablePromise<protocol$0.ReviewData> {
    return $Call.ByID(4119390853, session);
}

/**
 * Revive relaunches a dead-pane session on its surviving worktree.
 */
export function Revive(session: string): $CancellablePromise<protocol$0.ReviveData> {
    return $Call.ByID(325633556, session);
}

/**
 * Sessions returns the observer's session snapshot plus the activity feed.
 */
export function Sessions(): $CancellablePromise<protocol$0.SessionsData> {
    return $Call.ByID(545066424);
}

/**
 * StartDaemon spawns a detached `lola run` if the socket is dead, mirroring
 * daemonctl.spawnDaemon (own session, released, nil stdio). It waits up to 10s
 * for the socket to accept. A live daemon is left untouched.
 */
export function StartDaemon(): $CancellablePromise<void> {
    return $Call.ByID(2430978771);
}

/**
 * Status returns runtime + Linear health and per-poll state.
 */
export function Status(): $CancellablePromise<protocol$0.StatusData> {
    return $Call.ByID(960169243);
}

/**
 * StopDaemon asks a live daemon to shut down via {"cmd":"stop"} and waits for
 * the socket to go quiet. A down daemon is not an error.
 */
export function StopDaemon(): $CancellablePromise<void> {
    return $Call.ByID(2191041505);
}

/**
 * Tickets browses a project's Linear issues. scope is "mine" (default) or "team".
 */
export function Tickets(project: string, scope: string): $CancellablePromise<protocol$0.TicketsData> {
    return $Call.ByID(790605014, project, scope);
}
