// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DoctorService runs the same structured health checks the TUI's doctor overlay
 * does (internal/doctor.Check) — in-process, off the daemon, bounded to 15s.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Run loads config and executes the health checks. A missing/invalid config is
 * not fatal — Check tolerates a nil-ish config and reports it as a failed check.
 */
export function Run(): $CancellablePromise<$models.DoctorReportDTO> {
    return $Call.ByID(1595870839).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DoctorReportDTO.createFrom;
