// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigService from "./configservice.js";
import * as DaemonService from "./daemonservice.js";
import * as DoctorService from "./doctorservice.js";
import * as TermService from "./termservice.js";
export {
    ConfigService,
    DaemonService,
    DoctorService,
    TermService
};

export type {
    DoctorReportDTO,
    DoctorResultDTO,
    PollFormDTO,
    ProjectFormDTO,
    SettingsDTO
} from "./models.js";
