// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LinearService exposes the Linear metadata the poll editor needs to offer real
 * cascading pickers (team → project/cycle/state/label/assignee) instead of raw
 * UUIDs. It resolves the API key the same way the daemon/TUI do — from the
 * keychain or an env var, by *name* (secrets.LinearAPIKey) — so the key never
 * touches config, argv, or a log line. Per-team metadata is cached in memory;
 * pass refresh=true to bypass it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * TeamMeta fetches everything the poll form's dependent pickers need for a team.
 */
export function TeamMeta(teamID: string, refresh: boolean): $CancellablePromise<$models.LinearTeamMeta> {
    return $Call.ByID(1141327068, teamID, refresh).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Teams lists the workspace's teams for the top-level picker.
 */
export function Teams(): $CancellablePromise<$models.LinearTeam[]> {
    return $Call.ByID(1325983846).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LinearTeamMeta.createFrom;
const $$createType1 = $models.LinearTeam.createFrom;
const $$createType2 = $Create.Array($$createType1);
