// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CLIInfoDTO describes the `lola` CLI this app would run, so the UI can say
 * which binary the daemon comes from instead of leaving it invisible. Bundled
 * reports whether this .app ships a copy at all (a `wails3 dev` build does not),
 * which is what decides whether InstallCLI can do anything.
 */
export interface CLIInfoDTO {
    /**
     * resolved binary, "" when none
     */
    "path": string;

    /**
     * LOLA_BIN | PATH | bundled | ""
     */
    "source": string;

    /**
     * first line of `lola --version`
     */
    "version": string;
    "found": boolean;

    /**
     * why nothing resolved
     */
    "error": string;

    /**
     * this .app ships a CLI
     */
    "bundled": boolean;

    /**
     * version of the shipped copy
     */
    "bundledVersion": string;

    /**
     * Skewed reports that a PATH/LOLA_BIN binary was chosen whose version differs
     * from the bundled one. Not an error — a developer's own build is the
     * documented dev loop — but the cause of "the app has a feature the daemon
     * has never heard of", so it must be visible rather than diagnosed.
     */
    "skewed": boolean;

    /**
     * AppVersion is this app's compiled main.version, for the same comparison
     * from the other side.
     */
    "appVersion": string;
}

/**
 * CLIInstallDTO is InstallCLI's result. OnPATH=false means the symlink exists
 * but the user's shell will not find it without a profile edit — worth saying,
 * since the action would otherwise look like it silently did nothing.
 */
export interface CLIInstallDTO {
    "path": string;
    "onPath": boolean;
}

/**
 * ConnectCodeDTO is everything a phone needs to reach this machine's daemon:
 * the scannable token plus the same values as text.
 * 
 * Both shapes, deliberately. Code is what the Remote tab renders as a QR; the
 * loose fields are what a human reads out when the camera will not focus, the
 * camera permission was denied, or the client is a Simulator with no camera at
 * all. A QR must be a convenience and never the only way in.
 * 
 * Every field here is a secret while Key is set, and Code most of all — it
 * CONTAINS the key. Nothing on this side writes any of it to disk or to a log,
 * and the frontend keeps it behind an explicit reveal.
 */
export interface ConnectCodeDTO {
    "code": string;
    "hosts": string[] | null;
    "port": number;
    "pin": string;
    "key": string;
    "insecure": boolean;

    /**
     * Problem names why there is no code in one human sentence — the listener
     * is off, or nothing bound — so the tab renders a reason in place of the
     * code. It is a STATE rather than an error precisely because it is
     * actionable; a build with no bearer-key path at all IS an error, and
     * arrives as one.
     */
    "problem": string;
}

export interface DoctorReportDTO {
    "results": DoctorResultDTO[] | null;
    "summary": string;
    "ok": boolean;
}

export interface DoctorResultDTO {
    "name": string;
    "ok": boolean;
    "detail": string;
    "critical": boolean;
}

/**
 * GroupDTO is one [[group]] as the frontend sees it. Position is its index
 * among the top-level rows (see config.Group) — the sidebar draws folders beside
 * the projects, so a group's place is a value of its own.
 */
export interface GroupDTO {
    "name": string;
    "label": string;
    "position": number;
    "collapsed": boolean;
}

/**
 * InheritsDTO mirrors config.ProjectInherits: true means the project leaves the
 * key to [defaults], so the form shows the resolved value as a ghost and the
 * key is not written into the project's own table.
 */
export interface InheritsDTO {
    "symlinks": boolean;
    "postCreate": boolean;
    "env": boolean;
    "matchLabels": boolean;
    "matchMode": boolean;
    "onSentSetLabel": boolean;
    "blockedLabelId": boolean;
    "dedupMode": boolean;
    "prioritySort": boolean;
}

/**
 * LinearKeyStatusDTO describes WHERE the Linear key lives and whether it can be
 * resolved right now — never the key. Source is a human-readable origin
 * ("macOS Keychain (lola-linear)" / "environment variable LINEAR_API_KEY"), so
 * the settings screen can say why a key it cannot see is nonetheless fine.
 */
export interface LinearKeyStatusDTO {
    /**
     * config names a source
     */
    "configured": boolean;

    /**
     * that source actually yields a key
     */
    "resolvable": boolean;
    "source": string;

    /**
     * why it does not resolve, when it doesn't
     */
    "detail": string;
}

/**
 * LinearOption is one selectable {id,label} — the id is the Linear UUID stored
 * in config, the label is what the picker shows.
 */
export interface LinearOption {
    "id": string;
    "label": string;
}

export interface LinearTeam {
    "id": string;
    "key": string;
    "name": string;
}

export interface LinearTeamMeta {
    "projects": LinearOption[] | null;
    "cycles": LinearOption[] | null;
    "activeCycleId": string;
    "states": LinearOption[] | null;
    "labels": LinearOption[] | null;
    "members": LinearOption[] | null;
}

/**
 * PathInfoDTO is everything the project form derives from one picked folder.
 * Path is the checkout ROOT when there is one (picking a subdirectory still
 * configures the repository), else the directory as given.
 */
export interface PathInfoDTO {
    "path": string;
    "isRepo": boolean;
    "repo": string;
    "defaultBranch": string;
    "branches": string[] | null;
    "suggestedLabel": string;
    "suggestedId": string;
}

/**
 * ProjectFormDTO is the whole of one [[project]] — repository setup, Linear
 * polling filter and write-back — because a project IS the poll unit. The
 * values are the RESOLVED ones (see config.ResolveInheritance); Inherits says
 * which of them came from [defaults] rather than the project itself.
 */
export interface ProjectFormDTO {
    /**
     * Repository / worktree setup. Name is the project's ID — a path segment and
     * the prefix of every session/tmux name — while Label is the free-text
     * display string ("" falls back to Name). Changing Label here is an ordinary
     * save; changing Name is a RENAME and must go through
     * DaemonService.RenameProject FIRST, so that by the time SaveProject runs the
     * project on disk already answers to the new id.
     * The project's GROUP is deliberately absent: filing a project is done in
     * the sidebar, by dragging its row onto a folder, and a second place to set
     * it would let a stale form move a project nobody dragged. SaveProject leaves
     * Project.Group untouched.
     */
    "name": string;
    "label": string;
    "path": string;
    "repo": string;
    "defaultBranch": string;
    "branchPrefix": string;

    /**
     * ""=inherit | claude | codex | opencode
     */
    "agent": string;
    "symlinks": string[] | null;
    "postCreate": string[] | null;

    /**
     * DevCommands are the project's long-running dev processes, run by whichever
     * session is ACTIVE (one per project — see internal/daemon/dev.go). Not an
     * inheritable key: a dev command belongs to one repository.
     */
    "devCommands": string[] | null;

    /**
     * "KEY=value" lines
     */
    "env": string[] | null;

    /**
     * Linear polling filter.
     */
    "enabled": boolean;
    "teamId": string;
    "projectId": string;
    "cycleMode": string;
    "cycleId": string;
    "stateIds": string[] | null;
    "matchLabels": string[] | null;
    "matchMode": string;
    "assigneeMode": string;
    "assigneeUserId": string;
    "concurrencyCap": number;
    "dedupMode": string;
    "onSentSetLabel": string;

    /**
     * Linear write-back.
     */
    "onSpawnStateId": string;
    "onPrStateId": string;
    "onMergedStateId": string;
    "blockedLabelId": string;
    "commentOnSpawn": boolean;
    "commentOnPr": boolean;
    "commentOnMerged": boolean;
    "commentOnBlocked": boolean;
    "prRequiresChecks": boolean;
    "inherits": InheritsDTO;
    "isNew": boolean;
}

/**
 * ProjectLayoutDTO is the WHOLE sidebar arrangement — every configured project
 * in render order with its group, and every group in render order. Both lists
 * are complete: a partial layout is a bug in the caller, not a merge to
 * attempt, because the array positions ARE the order.
 */
export interface ProjectLayoutDTO {
    "groups": GroupDTO[] | null;
    "projects": ProjectPlacementDTO[] | null;
}

/**
 * ProjectPlacementDTO is one row of the sidebar arrangement: a project id and
 * the group it belongs to ("" = top level).
 */
export interface ProjectPlacementDTO {
    "name": string;
    "group": string;
}

/**
 * PushErrDTO is the payload of evtPushErr: which push-loop command failed and
 * the daemon's error text. Emitted only on a change (see pushLoop) so a
 * persistent failure is announced once, not every 2s.
 */
export interface PushErrDTO {
    "cmd": string;
    "msg": string;
}

export interface ReleaseEntryDTO {
    "version": string;
    "releaseNotes": string;
    "publishedAt": string;
}

/**
 * ReviewKindDTO describes ONE provider kind to the settings form: its id, the
 * heading it is drawn under, and which fields it actually has. The frontend
 * renders its Review tab from this list instead of a hardcoded array of kinds
 * plus a set of `p.provider === "…"` tests, so adding a review agent to
 * config.ReviewProviderKinds() makes the app offer it with no frontend edit —
 * which is the whole point of a pluggable catalog.
 */
export interface ReviewKindDTO {
    "kind": string;

    /**
     * Label is the section heading: the kind's name plus what it does.
     */
    "label": string;

    /**
     * Watch marks the poll/watermark shape: it has an author, and neither a
     * github transport nor a fallback chain (validation forbids both).
     */
    "watch": boolean;

    /**
     * CLI marks a kind that execs an external review CLI (command + base flag).
     */
    "cli": boolean;

    /**
     * Agent names the coding agent an agent-family kind reviews with, or "" when
     * the kind is not one (it is also the "offer a model field" test).
     */
    "agent": string;

    /**
     * RequiresCommand / RequiresAuthor mark the generic kinds, which carry no
     * built-in tool or bot of their own and are rejected by validation while
     * enabled-and-empty. The form marks the field required and says why.
     */
    "requiresCommand": boolean;
    "requiresAuthor": boolean;
}

/**
 * ReviewProviderDTO is one entry of the review provider catalog, flattened for
 * the settings form. Provider/Fallback/Transports are plain strings so the
 * frontend never needs the (unexported) provKind type; the Go side converts.
 */
export interface ReviewProviderDTO {
    /**
     * one of ReviewKinds()
     */
    "provider": string;
    "enabled": boolean;
    "onPrOpen": boolean;

    /**
     * cli family
     */
    "command": string;

    /**
     * cli family; empty appends no base
     */
    "baseFlag": string;

    /**
     * pass shapes
     */
    "timeoutSeconds": number;

    /**
     * agent family
     */
    "model": string;

    /**
     * watch family
     */
    "author": string;

    /**
     * lola (always) | github | linear
     */
    "transports": string[] | null;

    /**
     * github: anchored, resolvable threads instead of one comment
     */
    "githubInline": boolean;
    "notify": boolean;
    "sendToAgent": boolean;

    /**
     * pass shapes: run in a watchable "<session>-review" tmux session
     */
    "visible": boolean;

    /**
     * ordered pass kinds
     */
    "fallback": string[] | null;
}

export interface SettingsDTO {
    "globalCap": number;
    "concurrencyCap": number;

    /**
     * duration string, e.g. "60s"
     */
    "pollInterval": string;

    /**
     * claude|codex|opencode
     */
    "agent": string;
    "notifyDesktop": boolean;

    /**
     * env var NAME, never the URL
     */
    "slackWebhookEnv": string;
    "brainEnabled": boolean;
    "brainModel": string;
    "brainTimeout": number;
    "brainSummarizeEscalation": boolean;
    "brainSummarizeApproved": boolean;

    /**
     * [statusagent] — the display-only status interpreter.
     */
    "statusAgentEnabled": boolean;
    "statusAgentBin": string;
    "statusAgentModel": string;
    "statusAgentTimeout": number;
    "statusAgentMinInterval": number;
    "statusAgentMaxPerCycle": number;
    "statusAgentMinConfidence": number;
    "statusAgentIncludeTranscript": boolean;

    /**
     * [remote] — the phone listener (mobile/PLAN.md milestone 1). Three keys and
     * no inheritance, because a listener is a property of the MACHINE rather than
     * of a project. RemoteBind is either one of config.RemoteBinds or an IP
     * literal, so the form must be able to round-trip a literal it cannot offer
     * in a picker; coercing one back to a keyword on save would silently rebind
     * the daemon to a different set of interfaces.
     */
    "remoteEnabled": boolean;
    "remoteBind": string;
    "remotePort": number;
    "remoteInsecureLan": boolean;

    /**
     * ReviewProviders is the pluggable review catalog ([[review.provider]]),
     * resolved to the EFFECTIVE set (the real catalog, or the entries synthesized
     * from the legacy [review]/[coderabbit] tables). ReviewLegacy reports that the
     * config still carries the legacy tables and no catalog — in which state the
     * UI shows the providers read-only and offers MigrateReview.
     */
    "reviewProviders": ReviewProviderDTO[] | null;
    "reviewLegacy": boolean;

    /**
     * Project defaults: the [defaults] counterpart of each inheritable
     * [[project]] key. A project that does not override the key uses these.
     */
    "branchPrefix": string;
    "symlinks": string[] | null;
    "postCreate": string[] | null;

    /**
     * "KEY=value" lines
     */
    "env": string[] | null;
    "matchLabels": string[] | null;
    "matchMode": string;
    "onSentSetLabel": string;
    "blockedLabelId": string;
    "dedupMode": string;
    "prioritySort": string[] | null;
}

export interface SetupDTO {
    "linearKey": string;
    "projectName": string;
    "projectPath": string;
    "repo": string;
    "defaultBranch": string;
    "concurrencyCap": number;
    "globalCap": number;
    "pollInterval": string;
}

export interface SetupResultDTO {
    /**
     * key in the macOS Keychain
     */
    "keychainStored": boolean;

    /**
     * set when the key must come from an env var instead
     */
    "envVar": string;
    "message": string;
}

export interface UpdateInfoDTO {
    "available": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseNotes": string;
    "publishedAt": string;
    "downloadURL": string;
    "browserURL": string;
    "assetName": string;
    "assetSize": number;
    "releases": ReleaseEntryDTO[] | null;
}

/**
 * UpdateProgressDTO is the payload of evtUpdateProgress.
 */
export interface UpdateProgressDTO {
    "totalBytes": number;
    "downloadedBytes": number;
    "percentage": number;
    "status": string;
    "error"?: string;
    "filePath"?: string;
}

export interface UpdateSettingsDTO {
    "autoCheck": boolean;
    "lastCheckTime": string;
    "skippedVersion"?: string;
    "checkIntervalHours": number;
}
