// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DoctorReportDTO {
    "results": DoctorResultDTO[] | null;
    "summary": string;
    "ok": boolean;
}

export interface DoctorResultDTO {
    "name": string;
    "ok": boolean;
    "detail": string;
    "critical": boolean;
}

export interface PollFormDTO {
    "project": string;
    "enabled": boolean;
    "teamId": string;
    "projectId": string;
    "cycleMode": string;
    "cycleId": string;
    "stateIds": string[] | null;
    "matchLabels": string[] | null;
    "matchMode": string;
    "assigneeMode": string;
    "assigneeUserId": string;
    "concurrencyCap": number;
    "dedupMode": string;
    "onSentSetLabel": string;
    "onSpawnStateId": string;
    "onPrStateId": string;
    "onMergedStateId": string;
    "blockedLabelId": string;
    "commentOnSpawn": boolean;
    "commentOnPr": boolean;
    "commentOnMerged": boolean;
    "commentOnBlocked": boolean;
    "prRequiresChecks": boolean;
}

export interface ProjectFormDTO {
    "name": string;
    "path": string;
    "repo": string;
    "defaultBranch": string;

    /**
     * ""=inherit | claude | codex | opencode
     */
    "agent": string;
    "symlinks": string[] | null;
    "postCreate": string[] | null;

    /**
     * "KEY=value" lines
     */
    "env": string[] | null;
    "isNew": boolean;
}

export interface SettingsDTO {
    "globalCap": number;
    "concurrencyCap": number;

    /**
     * duration string, e.g. "60s"
     */
    "pollInterval": string;

    /**
     * claude|codex|opencode
     */
    "agent": string;
    "notifyDesktop": boolean;

    /**
     * env var NAME, never the URL
     */
    "slackWebhookEnv": string;
    "brainEnabled": boolean;
    "brainModel": string;
    "brainTimeout": number;
    "brainSummarizeEscalation": boolean;
    "brainSummarizeApproved": boolean;
    "reviewEnabled": boolean;
    "reviewCommand": string;
    "reviewOnPrOpen": boolean;
    "reviewSendToAgent": boolean;
    "reviewCommentOnLinear": boolean;
    "reviewTimeout": number;
    "crEnabled": boolean;
    "crAuthor": string;
    "crNotify": boolean;
    "crSendToAgent": boolean;
    "crCommentOnLinear": boolean;
}
