// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CLIInfoDTO describes the `lola` CLI this app would run, so the UI can say
 * which binary the daemon comes from instead of leaving it invisible. Bundled
 * reports whether this .app ships a copy at all (a `wails3 dev` build does not),
 * which is what decides whether InstallCLI can do anything.
 */
export class CLIInfoDTO {
    /**
     * resolved binary, "" when none
     */
    "path": string;

    /**
     * LOLA_BIN | PATH | bundled | ""
     */
    "source": string;

    /**
     * first line of `lola --version`
     */
    "version": string;
    "found": boolean;

    /**
     * why nothing resolved
     */
    "error": string;

    /**
     * this .app ships a CLI
     */
    "bundled": boolean;

    /**
     * version of the shipped copy
     */
    "bundledVersion": string;

    /**
     * Skewed reports that a PATH/LOLA_BIN binary was chosen whose version differs
     * from the bundled one. Not an error — a developer's own build is the
     * documented dev loop — but the cause of "the app has a feature the daemon
     * has never heard of", so it must be visible rather than diagnosed.
     */
    "skewed": boolean;

    /**
     * AppVersion is this app's compiled main.version, for the same comparison
     * from the other side.
     */
    "appVersion": string;

    /** Creates a new CLIInfoDTO instance. */
    constructor($$source: Partial<CLIInfoDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("bundled" in $$source)) {
            this["bundled"] = false;
        }
        if (!("bundledVersion" in $$source)) {
            this["bundledVersion"] = "";
        }
        if (!("skewed" in $$source)) {
            this["skewed"] = false;
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIInfoDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIInfoDTO($$parsedSource as Partial<CLIInfoDTO>);
    }
}

/**
 * CLIInstallDTO is InstallCLI's result. OnPATH=false means the symlink exists
 * but the user's shell will not find it without a profile edit — worth saying,
 * since the action would otherwise look like it silently did nothing.
 */
export class CLIInstallDTO {
    "path": string;
    "onPath": boolean;

    /** Creates a new CLIInstallDTO instance. */
    constructor($$source: Partial<CLIInstallDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("onPath" in $$source)) {
            this["onPath"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CLIInstallDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CLIInstallDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CLIInstallDTO($$parsedSource as Partial<CLIInstallDTO>);
    }
}

export class DoctorReportDTO {
    "results": DoctorResultDTO[];
    "summary": string;
    "ok": boolean;

    /** Creates a new DoctorReportDTO instance. */
    constructor($$source: Partial<DoctorReportDTO> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoctorReportDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DoctorReportDTO {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new DoctorReportDTO($$parsedSource as Partial<DoctorReportDTO>);
    }
}

export class DoctorResultDTO {
    "name": string;
    "ok": boolean;
    "detail": string;
    "critical": boolean;

    /** Creates a new DoctorResultDTO instance. */
    constructor($$source: Partial<DoctorResultDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("critical" in $$source)) {
            this["critical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoctorResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): DoctorResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DoctorResultDTO($$parsedSource as Partial<DoctorResultDTO>);
    }
}

/**
 * GroupDTO is one [[group]] as the frontend sees it. Position is its index
 * among the top-level rows (see config.Group) — the sidebar draws folders beside
 * the projects, so a group's place is a value of its own.
 */
export class GroupDTO {
    "name": string;
    "label": string;
    "position": number;
    "collapsed": boolean;

    /** Creates a new GroupDTO instance. */
    constructor($$source: Partial<GroupDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("collapsed" in $$source)) {
            this["collapsed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupDTO($$parsedSource as Partial<GroupDTO>);
    }
}

/**
 * InheritsDTO mirrors config.ProjectInherits: true means the project leaves the
 * key to [defaults], so the form shows the resolved value as a ghost and the
 * key is not written into the project's own table.
 */
export class InheritsDTO {
    "symlinks": boolean;
    "postCreate": boolean;
    "env": boolean;
    "matchLabels": boolean;
    "matchMode": boolean;
    "onSentSetLabel": boolean;
    "blockedLabelId": boolean;
    "dedupMode": boolean;
    "prioritySort": boolean;

    /** Creates a new InheritsDTO instance. */
    constructor($$source: Partial<InheritsDTO> = {}) {
        if (!("symlinks" in $$source)) {
            this["symlinks"] = false;
        }
        if (!("postCreate" in $$source)) {
            this["postCreate"] = false;
        }
        if (!("env" in $$source)) {
            this["env"] = false;
        }
        if (!("matchLabels" in $$source)) {
            this["matchLabels"] = false;
        }
        if (!("matchMode" in $$source)) {
            this["matchMode"] = false;
        }
        if (!("onSentSetLabel" in $$source)) {
            this["onSentSetLabel"] = false;
        }
        if (!("blockedLabelId" in $$source)) {
            this["blockedLabelId"] = false;
        }
        if (!("dedupMode" in $$source)) {
            this["dedupMode"] = false;
        }
        if (!("prioritySort" in $$source)) {
            this["prioritySort"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InheritsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): InheritsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InheritsDTO($$parsedSource as Partial<InheritsDTO>);
    }
}

/**
 * LinearKeyStatusDTO describes WHERE the Linear key lives and whether it can be
 * resolved right now — never the key. Source is a human-readable origin
 * ("macOS Keychain (lola-linear)" / "environment variable LINEAR_API_KEY"), so
 * the settings screen can say why a key it cannot see is nonetheless fine.
 */
export class LinearKeyStatusDTO {
    /**
     * config names a source
     */
    "configured": boolean;

    /**
     * that source actually yields a key
     */
    "resolvable": boolean;
    "source": string;

    /**
     * why it does not resolve, when it doesn't
     */
    "detail": string;

    /** Creates a new LinearKeyStatusDTO instance. */
    constructor($$source: Partial<LinearKeyStatusDTO> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("resolvable" in $$source)) {
            this["resolvable"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinearKeyStatusDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LinearKeyStatusDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinearKeyStatusDTO($$parsedSource as Partial<LinearKeyStatusDTO>);
    }
}

/**
 * LinearOption is one selectable {id,label} — the id is the Linear UUID stored
 * in config, the label is what the picker shows.
 */
export class LinearOption {
    "id": string;
    "label": string;

    /** Creates a new LinearOption instance. */
    constructor($$source: Partial<LinearOption> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinearOption instance from a string or object.
     */
    static createFrom($$source: any = {}): LinearOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinearOption($$parsedSource as Partial<LinearOption>);
    }
}

export class LinearTeam {
    "id": string;
    "key": string;
    "name": string;

    /** Creates a new LinearTeam instance. */
    constructor($$source: Partial<LinearTeam> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinearTeam instance from a string or object.
     */
    static createFrom($$source: any = {}): LinearTeam {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinearTeam($$parsedSource as Partial<LinearTeam>);
    }
}

export class LinearTeamMeta {
    "projects": LinearOption[];
    "cycles": LinearOption[];
    "activeCycleId": string;
    "states": LinearOption[];
    "labels": LinearOption[];
    "members": LinearOption[];

    /** Creates a new LinearTeamMeta instance. */
    constructor($$source: Partial<LinearTeamMeta> = {}) {
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }
        if (!("cycles" in $$source)) {
            this["cycles"] = [];
        }
        if (!("activeCycleId" in $$source)) {
            this["activeCycleId"] = "";
        }
        if (!("states" in $$source)) {
            this["states"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinearTeamMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): LinearTeamMeta {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField0_0($$parsedSource["projects"]);
        }
        if ("cycles" in $$parsedSource) {
            $$parsedSource["cycles"] = $$createField1_0($$parsedSource["cycles"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField3_0($$parsedSource["states"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField4_0($$parsedSource["labels"]);
        }
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField5_0($$parsedSource["members"]);
        }
        return new LinearTeamMeta($$parsedSource as Partial<LinearTeamMeta>);
    }
}

/**
 * PathInfoDTO is everything the project form derives from one picked folder.
 * Path is the checkout ROOT when there is one (picking a subdirectory still
 * configures the repository), else the directory as given.
 */
export class PathInfoDTO {
    "path": string;
    "isRepo": boolean;
    "repo": string;
    "defaultBranch": string;
    "branches": string[];
    "suggestedLabel": string;
    "suggestedId": string;

    /** Creates a new PathInfoDTO instance. */
    constructor($$source: Partial<PathInfoDTO> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("defaultBranch" in $$source)) {
            this["defaultBranch"] = "";
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }
        if (!("suggestedLabel" in $$source)) {
            this["suggestedLabel"] = "";
        }
        if (!("suggestedId" in $$source)) {
            this["suggestedId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PathInfoDTO {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField4_0($$parsedSource["branches"]);
        }
        return new PathInfoDTO($$parsedSource as Partial<PathInfoDTO>);
    }
}

/**
 * ProjectFormDTO is the whole of one [[project]] — repository setup, Linear
 * polling filter and write-back — because a project IS the poll unit. The
 * values are the RESOLVED ones (see config.ResolveInheritance); Inherits says
 * which of them came from [defaults] rather than the project itself.
 */
export class ProjectFormDTO {
    /**
     * Repository / worktree setup. Name is the project's ID — a path segment and
     * the prefix of every session/tmux name — while Label is the free-text
     * display string ("" falls back to Name). Changing Label here is an ordinary
     * save; changing Name is a RENAME and must go through
     * DaemonService.RenameProject FIRST, so that by the time SaveProject runs the
     * project on disk already answers to the new id.
     * The project's GROUP is deliberately absent: filing a project is done in
     * the sidebar, by dragging its row onto a folder, and a second place to set
     * it would let a stale form move a project nobody dragged. SaveProject leaves
     * Project.Group untouched.
     */
    "name": string;
    "label": string;
    "path": string;
    "repo": string;
    "defaultBranch": string;
    "branchPrefix": string;

    /**
     * ""=inherit | claude | codex | opencode
     */
    "agent": string;
    "symlinks": string[];
    "postCreate": string[];

    /**
     * DevCommands are the project's long-running dev processes, run by whichever
     * session is ACTIVE (one per project — see internal/daemon/dev.go). Not an
     * inheritable key: a dev command belongs to one repository.
     */
    "devCommands": string[];

    /**
     * "KEY=value" lines
     */
    "env": string[];

    /**
     * Linear polling filter.
     */
    "enabled": boolean;
    "teamId": string;
    "projectId": string;
    "cycleMode": string;
    "cycleId": string;
    "stateIds": string[];
    "matchLabels": string[];
    "matchMode": string;
    "assigneeMode": string;
    "assigneeUserId": string;
    "concurrencyCap": number;
    "dedupMode": string;
    "onSentSetLabel": string;

    /**
     * Linear write-back.
     */
    "onSpawnStateId": string;
    "onPrStateId": string;
    "onMergedStateId": string;
    "blockedLabelId": string;
    "commentOnSpawn": boolean;
    "commentOnPr": boolean;
    "commentOnMerged": boolean;
    "commentOnBlocked": boolean;
    "prRequiresChecks": boolean;
    "inherits": InheritsDTO;
    "isNew": boolean;

    /** Creates a new ProjectFormDTO instance. */
    constructor($$source: Partial<ProjectFormDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("defaultBranch" in $$source)) {
            this["defaultBranch"] = "";
        }
        if (!("branchPrefix" in $$source)) {
            this["branchPrefix"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("symlinks" in $$source)) {
            this["symlinks"] = [];
        }
        if (!("postCreate" in $$source)) {
            this["postCreate"] = [];
        }
        if (!("devCommands" in $$source)) {
            this["devCommands"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = [];
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("teamId" in $$source)) {
            this["teamId"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("cycleMode" in $$source)) {
            this["cycleMode"] = "";
        }
        if (!("cycleId" in $$source)) {
            this["cycleId"] = "";
        }
        if (!("stateIds" in $$source)) {
            this["stateIds"] = [];
        }
        if (!("matchLabels" in $$source)) {
            this["matchLabels"] = [];
        }
        if (!("matchMode" in $$source)) {
            this["matchMode"] = "";
        }
        if (!("assigneeMode" in $$source)) {
            this["assigneeMode"] = "";
        }
        if (!("assigneeUserId" in $$source)) {
            this["assigneeUserId"] = "";
        }
        if (!("concurrencyCap" in $$source)) {
            this["concurrencyCap"] = 0;
        }
        if (!("dedupMode" in $$source)) {
            this["dedupMode"] = "";
        }
        if (!("onSentSetLabel" in $$source)) {
            this["onSentSetLabel"] = "";
        }
        if (!("onSpawnStateId" in $$source)) {
            this["onSpawnStateId"] = "";
        }
        if (!("onPrStateId" in $$source)) {
            this["onPrStateId"] = "";
        }
        if (!("onMergedStateId" in $$source)) {
            this["onMergedStateId"] = "";
        }
        if (!("blockedLabelId" in $$source)) {
            this["blockedLabelId"] = "";
        }
        if (!("commentOnSpawn" in $$source)) {
            this["commentOnSpawn"] = false;
        }
        if (!("commentOnPr" in $$source)) {
            this["commentOnPr"] = false;
        }
        if (!("commentOnMerged" in $$source)) {
            this["commentOnMerged"] = false;
        }
        if (!("commentOnBlocked" in $$source)) {
            this["commentOnBlocked"] = false;
        }
        if (!("prRequiresChecks" in $$source)) {
            this["prRequiresChecks"] = false;
        }
        if (!("inherits" in $$source)) {
            this["inherits"] = (new InheritsDTO());
        }
        if (!("isNew" in $$source)) {
            this["isNew"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectFormDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectFormDTO {
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType4;
        const $$createField16_0 = $$createType4;
        const $$createField17_0 = $$createType4;
        const $$createField33_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("symlinks" in $$parsedSource) {
            $$parsedSource["symlinks"] = $$createField7_0($$parsedSource["symlinks"]);
        }
        if ("postCreate" in $$parsedSource) {
            $$parsedSource["postCreate"] = $$createField8_0($$parsedSource["postCreate"]);
        }
        if ("devCommands" in $$parsedSource) {
            $$parsedSource["devCommands"] = $$createField9_0($$parsedSource["devCommands"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField10_0($$parsedSource["env"]);
        }
        if ("stateIds" in $$parsedSource) {
            $$parsedSource["stateIds"] = $$createField16_0($$parsedSource["stateIds"]);
        }
        if ("matchLabels" in $$parsedSource) {
            $$parsedSource["matchLabels"] = $$createField17_0($$parsedSource["matchLabels"]);
        }
        if ("inherits" in $$parsedSource) {
            $$parsedSource["inherits"] = $$createField33_0($$parsedSource["inherits"]);
        }
        return new ProjectFormDTO($$parsedSource as Partial<ProjectFormDTO>);
    }
}

/**
 * ProjectLayoutDTO is the WHOLE sidebar arrangement — every configured project
 * in render order with its group, and every group in render order. Both lists
 * are complete: a partial layout is a bug in the caller, not a merge to
 * attempt, because the array positions ARE the order.
 */
export class ProjectLayoutDTO {
    "groups": GroupDTO[];
    "projects": ProjectPlacementDTO[];

    /** Creates a new ProjectLayoutDTO instance. */
    constructor($$source: Partial<ProjectLayoutDTO> = {}) {
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectLayoutDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectLayoutDTO {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField0_0($$parsedSource["groups"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new ProjectLayoutDTO($$parsedSource as Partial<ProjectLayoutDTO>);
    }
}

/**
 * ProjectPlacementDTO is one row of the sidebar arrangement: a project id and
 * the group it belongs to ("" = top level).
 */
export class ProjectPlacementDTO {
    "name": string;
    "group": string;

    /** Creates a new ProjectPlacementDTO instance. */
    constructor($$source: Partial<ProjectPlacementDTO> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectPlacementDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectPlacementDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectPlacementDTO($$parsedSource as Partial<ProjectPlacementDTO>);
    }
}

/**
 * PushErrDTO is the payload of evtPushErr: which push-loop command failed and
 * the daemon's error text. Emitted only on a change (see pushLoop) so a
 * persistent failure is announced once, not every 2s.
 */
export class PushErrDTO {
    "cmd": string;
    "msg": string;

    /** Creates a new PushErrDTO instance. */
    constructor($$source: Partial<PushErrDTO> = {}) {
        if (!("cmd" in $$source)) {
            this["cmd"] = "";
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushErrDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PushErrDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PushErrDTO($$parsedSource as Partial<PushErrDTO>);
    }
}

export class ReleaseEntryDTO {
    "version": string;
    "releaseNotes": string;
    "publishedAt": string;

    /** Creates a new ReleaseEntryDTO instance. */
    constructor($$source: Partial<ReleaseEntryDTO> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseEntryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseEntryDTO($$parsedSource as Partial<ReleaseEntryDTO>);
    }
}

/**
 * ReviewProviderDTO is one entry of the review provider catalog, flattened for
 * the settings form. Provider/Fallback/Transports are plain strings so the
 * frontend never needs the (unexported) provKind type; the Go side converts.
 */
export class ReviewProviderDTO {
    /**
     * coderabbit-cli | coderabbit-watch | claude-session
     */
    "provider": string;
    "enabled": boolean;
    "onPrOpen": boolean;

    /**
     * coderabbit-cli only
     */
    "command": string;

    /**
     * pass shapes
     */
    "timeoutSeconds": number;

    /**
     * claude-session only
     */
    "model": string;

    /**
     * coderabbit-watch only
     */
    "author": string;

    /**
     * lola (always) | github | linear
     */
    "transports": string[];

    /**
     * github: anchored, resolvable threads instead of one comment
     */
    "githubInline": boolean;
    "notify": boolean;
    "sendToAgent": boolean;

    /**
     * pass shapes: run in a watchable "<session>-review" tmux session
     */
    "visible": boolean;

    /**
     * ordered pass kinds
     */
    "fallback": string[];

    /** Creates a new ReviewProviderDTO instance. */
    constructor($$source: Partial<ReviewProviderDTO> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("onPrOpen" in $$source)) {
            this["onPrOpen"] = false;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("timeoutSeconds" in $$source)) {
            this["timeoutSeconds"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("transports" in $$source)) {
            this["transports"] = [];
        }
        if (!("githubInline" in $$source)) {
            this["githubInline"] = false;
        }
        if (!("notify" in $$source)) {
            this["notify"] = false;
        }
        if (!("sendToAgent" in $$source)) {
            this["sendToAgent"] = false;
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("fallback" in $$source)) {
            this["fallback"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewProviderDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewProviderDTO {
        const $$createField7_0 = $$createType4;
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField7_0($$parsedSource["transports"]);
        }
        if ("fallback" in $$parsedSource) {
            $$parsedSource["fallback"] = $$createField12_0($$parsedSource["fallback"]);
        }
        return new ReviewProviderDTO($$parsedSource as Partial<ReviewProviderDTO>);
    }
}

export class SettingsDTO {
    "globalCap": number;
    "concurrencyCap": number;

    /**
     * duration string, e.g. "60s"
     */
    "pollInterval": string;

    /**
     * claude|codex|opencode
     */
    "agent": string;
    "notifyDesktop": boolean;

    /**
     * env var NAME, never the URL
     */
    "slackWebhookEnv": string;
    "brainEnabled": boolean;
    "brainModel": string;
    "brainTimeout": number;
    "brainSummarizeEscalation": boolean;
    "brainSummarizeApproved": boolean;

    /**
     * [statusagent] — the display-only status interpreter.
     */
    "statusAgentEnabled": boolean;
    "statusAgentBin": string;
    "statusAgentModel": string;
    "statusAgentTimeout": number;
    "statusAgentMinInterval": number;
    "statusAgentMaxPerCycle": number;
    "statusAgentMinConfidence": number;
    "statusAgentIncludeTranscript": boolean;

    /**
     * ReviewProviders is the pluggable review catalog ([[review.provider]]),
     * resolved to the EFFECTIVE set (the real catalog, or the entries synthesized
     * from the legacy [review]/[coderabbit] tables). ReviewLegacy reports that the
     * config still carries the legacy tables and no catalog — in which state the
     * UI shows the providers read-only and offers MigrateReview.
     */
    "reviewProviders": ReviewProviderDTO[];
    "reviewLegacy": boolean;

    /**
     * Project defaults: the [defaults] counterpart of each inheritable
     * [[project]] key. A project that does not override the key uses these.
     */
    "branchPrefix": string;
    "symlinks": string[];
    "postCreate": string[];

    /**
     * "KEY=value" lines
     */
    "env": string[];
    "matchLabels": string[];
    "matchMode": string;
    "onSentSetLabel": string;
    "blockedLabelId": string;
    "dedupMode": string;
    "prioritySort": string[];

    /** Creates a new SettingsDTO instance. */
    constructor($$source: Partial<SettingsDTO> = {}) {
        if (!("globalCap" in $$source)) {
            this["globalCap"] = 0;
        }
        if (!("concurrencyCap" in $$source)) {
            this["concurrencyCap"] = 0;
        }
        if (!("pollInterval" in $$source)) {
            this["pollInterval"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("notifyDesktop" in $$source)) {
            this["notifyDesktop"] = false;
        }
        if (!("slackWebhookEnv" in $$source)) {
            this["slackWebhookEnv"] = "";
        }
        if (!("brainEnabled" in $$source)) {
            this["brainEnabled"] = false;
        }
        if (!("brainModel" in $$source)) {
            this["brainModel"] = "";
        }
        if (!("brainTimeout" in $$source)) {
            this["brainTimeout"] = 0;
        }
        if (!("brainSummarizeEscalation" in $$source)) {
            this["brainSummarizeEscalation"] = false;
        }
        if (!("brainSummarizeApproved" in $$source)) {
            this["brainSummarizeApproved"] = false;
        }
        if (!("statusAgentEnabled" in $$source)) {
            this["statusAgentEnabled"] = false;
        }
        if (!("statusAgentBin" in $$source)) {
            this["statusAgentBin"] = "";
        }
        if (!("statusAgentModel" in $$source)) {
            this["statusAgentModel"] = "";
        }
        if (!("statusAgentTimeout" in $$source)) {
            this["statusAgentTimeout"] = 0;
        }
        if (!("statusAgentMinInterval" in $$source)) {
            this["statusAgentMinInterval"] = 0;
        }
        if (!("statusAgentMaxPerCycle" in $$source)) {
            this["statusAgentMaxPerCycle"] = 0;
        }
        if (!("statusAgentMinConfidence" in $$source)) {
            this["statusAgentMinConfidence"] = 0;
        }
        if (!("statusAgentIncludeTranscript" in $$source)) {
            this["statusAgentIncludeTranscript"] = false;
        }
        if (!("reviewProviders" in $$source)) {
            this["reviewProviders"] = [];
        }
        if (!("reviewLegacy" in $$source)) {
            this["reviewLegacy"] = false;
        }
        if (!("branchPrefix" in $$source)) {
            this["branchPrefix"] = "";
        }
        if (!("symlinks" in $$source)) {
            this["symlinks"] = [];
        }
        if (!("postCreate" in $$source)) {
            this["postCreate"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = [];
        }
        if (!("matchLabels" in $$source)) {
            this["matchLabels"] = [];
        }
        if (!("matchMode" in $$source)) {
            this["matchMode"] = "";
        }
        if (!("onSentSetLabel" in $$source)) {
            this["onSentSetLabel"] = "";
        }
        if (!("blockedLabelId" in $$source)) {
            this["blockedLabelId"] = "";
        }
        if (!("dedupMode" in $$source)) {
            this["dedupMode"] = "";
        }
        if (!("prioritySort" in $$source)) {
            this["prioritySort"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsDTO {
        const $$createField19_0 = $$createType11;
        const $$createField22_0 = $$createType4;
        const $$createField23_0 = $$createType4;
        const $$createField24_0 = $$createType4;
        const $$createField25_0 = $$createType4;
        const $$createField30_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reviewProviders" in $$parsedSource) {
            $$parsedSource["reviewProviders"] = $$createField19_0($$parsedSource["reviewProviders"]);
        }
        if ("symlinks" in $$parsedSource) {
            $$parsedSource["symlinks"] = $$createField22_0($$parsedSource["symlinks"]);
        }
        if ("postCreate" in $$parsedSource) {
            $$parsedSource["postCreate"] = $$createField23_0($$parsedSource["postCreate"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField24_0($$parsedSource["env"]);
        }
        if ("matchLabels" in $$parsedSource) {
            $$parsedSource["matchLabels"] = $$createField25_0($$parsedSource["matchLabels"]);
        }
        if ("prioritySort" in $$parsedSource) {
            $$parsedSource["prioritySort"] = $$createField30_0($$parsedSource["prioritySort"]);
        }
        return new SettingsDTO($$parsedSource as Partial<SettingsDTO>);
    }
}

export class SetupDTO {
    "linearKey": string;
    "projectName": string;
    "projectPath": string;
    "repo": string;
    "defaultBranch": string;
    "concurrencyCap": number;
    "globalCap": number;
    "pollInterval": string;

    /** Creates a new SetupDTO instance. */
    constructor($$source: Partial<SetupDTO> = {}) {
        if (!("linearKey" in $$source)) {
            this["linearKey"] = "";
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("defaultBranch" in $$source)) {
            this["defaultBranch"] = "";
        }
        if (!("concurrencyCap" in $$source)) {
            this["concurrencyCap"] = 0;
        }
        if (!("globalCap" in $$source)) {
            this["globalCap"] = 0;
        }
        if (!("pollInterval" in $$source)) {
            this["pollInterval"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupDTO($$parsedSource as Partial<SetupDTO>);
    }
}

export class SetupResultDTO {
    /**
     * key in the macOS Keychain
     */
    "keychainStored": boolean;

    /**
     * set when the key must come from an env var instead
     */
    "envVar": string;
    "message": string;

    /** Creates a new SetupResultDTO instance. */
    constructor($$source: Partial<SetupResultDTO> = {}) {
        if (!("keychainStored" in $$source)) {
            this["keychainStored"] = false;
        }
        if (!("envVar" in $$source)) {
            this["envVar"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupResultDTO($$parsedSource as Partial<SetupResultDTO>);
    }
}

export class UpdateInfoDTO {
    "available": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseNotes": string;
    "publishedAt": string;
    "downloadURL": string;
    "browserURL": string;
    "assetName": string;
    "assetSize": number;
    "releases": ReleaseEntryDTO[];

    /** Creates a new UpdateInfoDTO instance. */
    constructor($$source: Partial<UpdateInfoDTO> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("browserURL" in $$source)) {
            this["browserURL"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }
        if (!("releases" in $$source)) {
            this["releases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfoDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfoDTO {
        const $$createField9_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("releases" in $$parsedSource) {
            $$parsedSource["releases"] = $$createField9_0($$parsedSource["releases"]);
        }
        return new UpdateInfoDTO($$parsedSource as Partial<UpdateInfoDTO>);
    }
}

/**
 * UpdateProgressDTO is the payload of evtUpdateProgress.
 */
export class UpdateProgressDTO {
    "totalBytes": number;
    "downloadedBytes": number;
    "percentage": number;
    "status": string;
    "error"?: string;
    "filePath"?: string;

    /** Creates a new UpdateProgressDTO instance. */
    constructor($$source: Partial<UpdateProgressDTO> = {}) {
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("percentage" in $$source)) {
            this["percentage"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProgressDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProgressDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProgressDTO($$parsedSource as Partial<UpdateProgressDTO>);
    }
}

export class UpdateSettingsDTO {
    "autoCheck": boolean;
    "lastCheckTime": string;
    "skippedVersion"?: string;
    "checkIntervalHours": number;

    /** Creates a new UpdateSettingsDTO instance. */
    constructor($$source: Partial<UpdateSettingsDTO> = {}) {
        if (!("autoCheck" in $$source)) {
            this["autoCheck"] = false;
        }
        if (!("lastCheckTime" in $$source)) {
            this["lastCheckTime"] = "";
        }
        if (!("checkIntervalHours" in $$source)) {
            this["checkIntervalHours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSettingsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSettingsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSettingsDTO($$parsedSource as Partial<UpdateSettingsDTO>);
    }
}

// Private type creation functions
const $$createType0 = DoctorResultDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = LinearOption.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = InheritsDTO.createFrom;
const $$createType6 = GroupDTO.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ProjectPlacementDTO.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ReviewProviderDTO.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ReleaseEntryDTO.createFrom;
const $$createType13 = $Create.Array($$createType12);
