// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TermService bridges lola's isolated tmux server (tmux -L lola) to the webview.
 * It serves the sessions overview two ways, matching the WebGL-context ceiling
 * (~16 live GPU contexts per page): read-only *snapshots* for the many grid
 * tiles (cheap capture-pane, no tmux client, no resize), and a live interactive
 * *PTY attach* for the one focused terminal (streamed as coalesced base64 chunks
 * the frontend decodes straight into an xterm WebGL instance).
 * 
 * Snapshots never attach a client, so they can never resize or disturb a running
 * agent. Attaching does create a tmux client; we size it to the caller's xterm
 * and rely on tmux's window-size=latest so a second client (e.g. the TUI embed)
 * doesn't thrash the pane.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * Attach starts an interactive `tmux attach` to the named session in a PTY sized
 * cols×rows and streams its output to the frontend as base64 chunks on the event
 * `pty:<name>`, coalesced to one emit per ~16ms so a chatty agent can't saturate
 * the webview. Re-attaching an already-live stream tears the old one down first.
 * Returns the stream ID (the session name) the frontend uses for Write/Resize/
 * Detach and the event subscription.
 */
export function Attach(name: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(762999658, name, cols, rows);
}

/**
 * Capture returns a read-only snapshot of a session's tmux pane with ANSI
 * escapes preserved (capture-pane -p -e), the last `lines` rows (0 → 200). The
 * tmux session name is the lola session ID (SessionInfo.TmuxName). This never
 * attaches a client, so it cannot resize or disturb the agent.
 */
export function Capture(name: string, lines: number): $CancellablePromise<string> {
    return $Call.ByID(2391851095, name, lines);
}

/**
 * CaptureMany snapshots several panes in one call so the grid refresh is a single
 * round-trip from the frontend. A pane that fails to capture (session gone) is
 * simply omitted from the map rather than failing the whole batch.
 */
export function CaptureMany(names: string[], lines: number): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(261382224, names, lines).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Detach closes the PTY: the tmux client detaches (the agent keeps running,
 * untouched) and the stream's goroutines wind down. Idempotent.
 */
export function Detach(name: string): $CancellablePromise<void> {
    return $Call.ByID(2614283856, name);
}

/**
 * Resize propagates an xterm resize to the PTY so the remote app reflows.
 */
export function Resize(name: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2185863351, name, cols, rows);
}

/**
 * SetApp injects the Wails emitter. Called once from main before Run.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2962051340, app);
}

/**
 * Write forwards keystrokes (xterm onData, always valid UTF-8) to the PTY.
 */
export function Write(name: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3287491394, name, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
