// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TermService bridges lola's isolated tmux server (tmux -L lola) to the webview.
 * It serves the sessions overview two ways, matching the WebGL-context ceiling
 * (~16 live GPU contexts per page): read-only *snapshots* for the many grid
 * tiles (cheap capture-pane, no tmux client, no resize), and a live interactive
 * *PTY attach* for the one focused terminal (streamed as coalesced base64 chunks
 * the frontend decodes straight into an xterm WebGL instance).
 * 
 * Snapshots never attach a client, so they can never resize or disturb a running
 * agent. Attaching does create a tmux client; we size it to the caller's xterm
 * and rely on tmux's window-size=latest so a second client (e.g. the TUI embed)
 * doesn't thrash the pane.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * Attach starts an interactive `tmux attach` to the named session in a PTY sized
 * cols×rows and streams its output to the frontend as base64 chunks on the event
 * `pty:<name>`, coalesced to one emit per ~16ms so a chatty agent can't saturate
 * the webview. Re-attaching an already-live stream tears the old one down first.
 * Returns the stream ID (the session name) the frontend uses for Write/Resize/
 * Detach and the event subscription.
 */
export function Attach(name: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(762999658, name, cols, rows);
}

/**
 * Capture returns a read-only snapshot of a session's tmux pane with ANSI
 * escapes preserved (capture-pane -p -e), the last `lines` rows (0 → 200). The
 * tmux session name is the lola session ID (SessionInfo.TmuxName). This never
 * attaches a client, so it cannot resize or disturb the agent.
 */
export function Capture(name: string, lines: number): $CancellablePromise<string> {
    return $Call.ByID(2391851095, name, lines);
}

/**
 * CaptureMany snapshots several panes in one call so the grid refresh is a single
 * round-trip from the frontend. Panes are captured concurrently, so the batch is
 * bounded by the slowest capture rather than their sum. A pane that fails to
 * capture (session gone) is simply omitted from the map rather than failing the
 * whole batch.
 */
export function CaptureMany(names: string[], lines: number): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(261382224, names, lines).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CloseSessionShells kills every shell tmux session for a lola session — called
 * when the session is killed so its shells (rooted in the now-removed worktree)
 * don't linger as orphan tabs in either surface. Best-effort.
 */
export function CloseSessionShells(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3843539944, sessionID);
}

/**
 * CloseShell tears down one shell: detach any live stream, then kill its tmux
 * session so it doesn't linger after the tab is closed. Idempotent — killing an
 * absent session is a no-op. shell is the full "-shell" tmux name; the marker
 * guard keeps this from ever killing an agent session.
 */
export function CloseShell(shell: string): $CancellablePromise<void> {
    return $Call.ByID(4064217889, shell);
}

/**
 * Detach closes the PTY: the tmux client detaches (the agent keeps running,
 * untouched) and the stream's goroutines wind down. Idempotent. Marks the stream
 * detached FIRST so the read loop's teardown (unblocked by the close) knows this
 * was intentional and suppresses the exit event — detaching a shell tab must NOT
 * look like the shell exiting, or switching tabs would kill the shell.
 */
export function Detach(name: string): $CancellablePromise<void> {
    return $Call.ByID(2614283856, name);
}

/**
 * Resize propagates an xterm resize to the PTY so the remote app reflows. Like
 * Write, a resize aimed at an already-gone stream is a no-op (the ResizeObserver
 * can fire once more as the terminal tears down) rather than an error.
 */
export function Resize(name: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2185863351, name, cols, rows);
}

/**
 * Scroll moves the named pane's view back through its history: lines > 0 scrolls
 * BACK (up), lines < 0 forward again, zero is a no-op. It is the whole reason a
 * lola terminal scrolls in the app: `tmux attach` runs on the alternate screen,
 * so xterm.js has no scrollback of its own and its fallback for that case turns
 * the wheel into cursor keys — which walks the AGENT's input history instead of
 * scrolling anything.
 * 
 * The work is (*tmux.Client).ScrollPane's, shared with the TUI, and it is what
 * decides WHICH history to move: the program's own (an agent on the alternate
 * screen keeps its transcript itself and asks for the wheel) or tmux's copy mode
 * (a plain shell). All this needs to know is which one happened, because only
 * copy mode leaves a mode behind for the next keystroke to cancel.
 */
export function Scroll(name: string, lines: number): $CancellablePromise<void> {
    return $Call.ByID(1163232830, name, lines);
}

/**
 * SetApp injects the Wails emitter. Called once from main before Run.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2962051340, app);
}

/**
 * Shell ensures the named shell tmux session exists, rooted in worktree, and
 * returns its name so the frontend can Attach to it exactly like the agent pane.
 * The desktop equivalent of the TUI's shell. The frontend owns the name (and its
 * uniqueness); Shell only validates it carries the shell marker. Idempotent: an
 * already-running session of that name is reused, so a re-open re-attaches.
 */
export function Shell(shell: string, worktree: string): $CancellablePromise<string> {
    return $Call.ByID(1084872819, shell, worktree);
}

/**
 * Shells lists a lola session's auxiliary tmux sessions on the lola server: its
 * dev tabs ("<id>-dev-N", the project's dev_commands — the daemon owns their
 * lifetime, see internal/daemon/dev.go), then its shells ("<id>-shell-N", sorted
 * by their trailing index), then its review pane ("<id>-review") when a visible
 * review pass has opened one. Both the app
 * and the TUI discover the SAME sessions, so a shell opened in either shows up
 * as a tab in the other — and a review the daemon started shows up in both
 * without either having to be told. An empty result (or a tmux error) simply
 * means no auxiliary sessions.
 */
export function Shells(sessionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3412002816, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Write forwards keystrokes (xterm onData, always valid UTF-8) to the PTY. A
 * write to a stream that has already ended (the terminal exited, tearing itself
 * down a frame before xterm's last onData) is a silent no-op, NOT an error: the
 * keystroke has nowhere to go and surfacing it would spam the log on every exit.
 */
export function Write(name: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3287491394, name, data);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
