// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService is the bound bridge between the pure internal/update package and
 * the frontend: it checks the public repo's GitHub Releases, streams the DMG
 * download as events, and swaps the running .app. It holds the app so it can
 * emit progress and quit for the install; SetApp wires it after the app exists.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates queries the latest release and records the check time. It
 * carries a skipped flag out via the DTO's Available field being left true —
 * the frontend decides whether to surface it against the skipped version.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfoDTO> {
    return $Call.ByID(670986527);
}

/**
 * DownloadUpdate fetches the DMG at url into the user's Downloads folder,
 * emitting evtUpdateProgress as it goes, and returns the saved path. It blocks
 * until the download completes (the frontend drives it off progress events).
 */
export function DownloadUpdate(url: string): $CancellablePromise<string> {
    return $Call.ByID(943505489, url);
}

/**
 * GetRecentReleases returns the newest published releases for a changelog view.
 */
export function GetRecentReleases(count: number): $CancellablePromise<$models.ReleaseEntryDTO[] | null> {
    return $Call.ByID(3960301741, count);
}

/**
 * GetUpdateSettings returns the persisted preferences.
 */
export function GetUpdateSettings(): $CancellablePromise<$models.UpdateSettingsDTO> {
    return $Call.ByID(1504430752);
}

/**
 * GetVersion returns the compiled-in app version (the ldflag-injected
 * main.version; "dev" for un-tagged local builds).
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2538966544);
}

/**
 * InstallAndRestart mounts the DMG, stages the new bundle, launches the detached
 * swap script, then quits so the script can replace and relaunch the app.
 */
export function InstallAndRestart(dmgPath: string): $CancellablePromise<void> {
    return $Call.ByID(2393830319, dmgPath);
}

/**
 * IsVersionSkipped reports whether v is the currently skipped version.
 */
export function IsVersionSkipped(v: string): $CancellablePromise<boolean> {
    return $Call.ByID(4209345560, v);
}

/**
 * SetApp gives the service the emitter/quit handle (called once in main).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1525297243, app);
}

/**
 * SetUpdateSettings persists the AutoCheck toggle and interval (last-check and
 * skipped-version are owned by the check/skip paths, so they are preserved).
 */
export function SetUpdateSettings($in: $models.UpdateSettingsDTO): $CancellablePromise<void> {
    return $Call.ByID(2317555836, $in);
}

/**
 * ShouldAutoCheck reports whether the startup auto-check is due (respects the
 * AutoCheck toggle and the interval).
 */
export function ShouldAutoCheck(): $CancellablePromise<boolean> {
    return $Call.ByID(1901937160);
}

/**
 * SkipVersion records a version the user chose not to be nagged about.
 */
export function SkipVersion(v: string): $CancellablePromise<void> {
    return $Call.ByID(1865952185, v);
}
