// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodeRabbitData is Response.Data for cmd=coderabbit: the outcome of a forced
 * PR-comment watch poll, flattened to render-ready fields for the CLI. Message is
 * the short human-readable line the CLI prints. Ran reports whether the poll ran
 * (a gh call was made); Found is true when it surfaced at least one comment;
 * Skipped names why the poll did not run (watch disabled / no open PR), ""
 * otherwise. Comments is the full, size-capped comment text (UNTRUSTED,
 * attacker-authorable) when Found — present so a caller can display it; empty on
 * none/skipped.
 */
export interface CodeRabbitData {
    "ran": boolean;
    "found": boolean;
    "skipped"?: string;
    "comments"?: string;
    "message"?: string;
}

/**
 * Event is one session status transition surfaced in the activity feed,
 * flattened to render-ready strings so the TUI needs no scm/session imports.
 * From is the prior derived status ("" means the session was just spawned); To
 * is the new derived status; Ago is a human duration since the transition
 * (e.g. "2m", formatted daemon-side against the request time).
 */
export interface Event {
    "id": string;

    /**
     * Linear identifier, e.g. ENG-123 ("" when unknown)
     */
    "issue": string;

    /**
     * Linear issue title, "" when unknown
     */
    "title"?: string;
    "from": string;
    "to": string;
    "ago": string;
}

/**
 * KillData is Response.Data for cmd=kill. Removed reports whether the worktree
 * was actually removed (false when the project is gone from config so there was
 * nothing safe to target, or on a dirty-refused kill — but a dirty refusal is
 * returned as an error, not a KillData). Worktree is the worktree dir the kill
 * targeted (removed or kept), "" when none applied. Message is a short
 * human-readable outcome for the CLI/TUI to print.
 */
export interface KillData {
    "removed": boolean;
    "worktree"?: string;
    "message"?: string;
}

/**
 * Match describes one matched issue and what the tick did (or would do) with it.
 */
export interface Match {
    "identifier": string;
    "title": string;

    /**
     * spawned|would-spawn|skipped
     */
    "action": string;

    /**
     * dedup-label|dedup-seen|in-flight|capped|error
     */
    "reason"?: string;
}

/**
 * OpenData is Response.Data for cmd=open: a branch/PR manually checked out into
 * a throwaway DETACHED worktree with a plain shell (no coding agent), for running
 * and testing a PR. SessionID is the created session's ID (and its tmux target),
 * Worktree the checkout directory, Branch the human-readable label opened, and
 * Message a short human-readable outcome for the CLI/TUI to print.
 */
export interface OpenData {
    "sessionId": string;
    "worktree"?: string;
    "branch"?: string;
    "message"?: string;
}

/**
 * OpenManualArgs is the argument payload for cmd=openManual: create a NEW branch
 * (off Base, empty → the project's default branch) in a fresh worktree. With
 * Agent set it launches the coding agent (seeded with Prompt); otherwise a plain
 * shell. The reply is the shared OpenData.
 */
export interface OpenManualArgs {
    "project": string;
    "branch": string;
    "base"?: string;

    /**
     * launch the coding agent instead of a shell
     */
    "agent"?: boolean;

    /**
     * seed prompt when Agent is set
     */
    "prompt"?: string;
}

/**
 * OpenPrArgs is the argument payload for cmd=openPr: open a PR's head branch as a
 * TRACKING worktree and launch the coding agent on it (so it can push back).
 * IsFork is set by the client for a fork PR — the daemon refuses those (no
 * push-back to a fork). The reply is the shared OpenData.
 */
export interface OpenPrArgs {
    "project": string;
    "branch": string;
    "number"?: number;
    "isFork"?: boolean;
}

/**
 * OpenTicketArgs is the argument payload for cmd=openTicket: start a Linear issue
 * on demand — a worktree + agent, deduped exactly like a poll dispatch so a
 * running poll cannot spawn it twice. The reply is the shared OpenData.
 */
export interface OpenTicketArgs {
    "project": string;
    "identifier": string;
    "uuid": string;
    "branch"?: string;
    "title"?: string;
}

/**
 * PaneChoice is one enumerated option the agent offered at its prompt. Key is
 * what the human sends to select it (a menu number/letter); Label is the
 * human-readable option text.
 */
export interface PaneChoice {
    "key": string;
    "label": string;
}

/**
 * PaneData is Response.Data for cmd=pane (PLAN P7): the captured tmux pane text
 * plus the attention parser's read of it, flattened so the TUI renders an
 * actionable answer card without importing internal/attention (and so protocol
 * stays dependency-free). Text is the rendered pane (ANSI preserved, as
 * capture-pane -e returns it). HasQuestion reports whether a prompt was
 * detected; when true, Prompt is the question line, Choices enumerates any
 * pick-one options the agent offered (empty for a pure free-text prompt),
 * and FreeForm reports whether a typed reply is expected. Both a choice list and
 * FreeForm can be surfaced; the human either picks a Choice.Key or types text,
 * and either is delivered back via cmd=answer.
 */
export interface PaneData {
    "text": string;
    "hasQuestion": boolean;
    "prompt"?: string;
    "choices"?: PaneChoice[] | null;
    "freeForm"?: boolean;
}

/**
 * PollOnceData is Response.Data for cmd=pollOnce.
 */
export interface PollOnceData {
    "poll": string;
    "dryRun": boolean;
    "matches": Match[] | null;
}

export interface PollStatus {
    "name": string;
    "enabled": boolean;
    "lastRun": string;
    "lastSpawn": string;

    /**
     * tick currently executing
     */
    "running": boolean;
    "lastError"?: string;
}

/**
 * PrRow is one open PR for the picker.
 */
export interface PrRow {
    "number": number;
    "title": string;
    "author": string;
    "branch": string;
    "isDraft": boolean;
    "isFork": boolean;

    /**
     * pass|fail|pending|none
     */
    "checks": string;
    "review": string;
    "url": string;

    /**
     * scm.DeriveStatus vocabulary
     */
    "status": string;

    /**
     * a lola session already holds this branch
     */
    "alreadyOpen": boolean;
}

/**
 * ProjectInfo is one configured project flattened to render-ready fields.
 */
export interface ProjectInfo {
    /**
     * Name is the project's ID — what paths, tmux names and every other
     * name-keyed protocol field use. Label is its display string, "" when the
     * project has none (render Name then).
     */
    "name": string;
    "label"?: string;
    "path": string;
    "repo": string;
    "defaultBranch": string;

    /**
     * Per-PROJECT agent health (not the default agent): AgentBin is the resolved
     * coding-agent binary for this project (its override → [defaults].agent →
     * claude), AgentOK whether it plus tmux+git all resolve on PATH, AgentErr the
     * reason when not. The TUI gates this project's spawn verbs on AgentOK.
     */
    "agent": string;
    "agentBin": string;
    "agentOk": boolean;
    "agentErr"?: string;

    /**
     * PathOK is whether Path exists and is a git checkout (a .git entry); a
     * runtime probe, deliberately NOT config's job. RepoConfigured is whether a
     * GitHub "owner/name" repo is set (needed by the PR picker).
     */
    "pathOk": boolean;
    "repoConfigured": boolean;

    /**
     * Poll rollup: how many polls this project drives and how many are enabled,
     * their names, and the newest LastRun / first LastError across them.
     */
    "pollCount": number;
    "pollsEnabled": number;
    "polls"?: string[] | null;
    "lastRun": string;
    "lastError"?: string;

    /**
     * Session rollup for this project (from the observer's snapshot store):
     * Sessions total, LiveCounted occupying a slot, NeedsYou parked on a human,
     * CIRed failing CI, OpenPRs with an open PR.
     */
    "sessions": number;
    "liveCounted": number;
    "needsYou": number;
    "ciRed": number;
    "openPrs": number;
}

/**
 * ProjectsData is Response.Data for cmd=projects: the daemon's cached view of
 * every configured [[project]] decorated with live status. Like cmd=sessions it
 * is served from in-memory snapshots (config + status tracker + session store)
 * and does not exec gh/tmux/git — the only filesystem touches are cheap
 * LookPath (agent health) and os.Stat (path/.git probe), never a subprocess. The
 * TUI renders the project list from its OWN config and merely decorates rows
 * with these facts, so the home screen stays navigable when the daemon is down.
 */
export interface ProjectsData {
    "projects": ProjectInfo[] | null;
}

/**
 * PrsData is Response.Data for cmd=prs: the open pull requests for a project's
 * repo, flattened for the picker. Served from a short-TTL cache (the daemon
 * execs `gh pr list` on a miss); AgeSeconds/Stale let the TUI show freshness.
 */
export interface PrsData {
    "repo": string;
    "prs": PrRow[] | null;

    /**
     * how old the served snapshot is
     */
    "ageSeconds": number;

    /**
     * served past its TTL (a refresh is running/failed)
     */
    "stale": boolean;
}

/**
 * RenameProjectData is Response.Data for cmd=renameProject. Message is a short
 * human-readable outcome; Blockers names the live sessions that made the daemon
 * refuse (empty on success), so the client can tell the human exactly what to
 * finish before renaming.
 */
export interface RenameProjectData {
    "from": string;
    "to": string;
    "blockers"?: string[] | null;
    "message"?: string;
}

/**
 * ReviewData is Response.Data for cmd=review (PLAN P9): the outcome of a forced
 * QA review pass, flattened to render-ready fields for the CLI. Message is the
 * short human-readable line the CLI prints. Ran reports whether the review exec
 * ran; Clean is true only when it ran and found nothing; Skipped names why the
 * pass did not run (review disabled / no project), "" otherwise. Findings is the
 * full trimmed, size-capped findings text (UNTRUSTED, diff-derived) when the run
 * found issues — present so a caller can display it; empty on clean/skipped.
 */
export interface ReviewData {
    "ran": boolean;
    "clean": boolean;
    "skipped"?: string;
    "findings"?: string;
    "message"?: string;
}

/**
 * ReviveData is Response.Data for cmd=revive: a dead session relaunched on its
 * kept worktree. Revived is always true on the success path (a failure is
 * returned as an error instead). TmuxName is the revived session's tmux target
 * and Message is a short human-readable outcome for the CLI/TUI to print.
 */
export interface ReviveData {
    "revived": boolean;
    "tmuxName"?: string;
    "message"?: string;
}

/**
 * SessionInfo is one observed session, flattened to render-ready strings and
 * ints so the TUI never needs scm/session imports or re-derivation.
 */
export interface SessionInfo {
    "id": string;
    "project": string;

    /**
     * Linear identifier, e.g. ENG-123
     */
    "issue": string;

    /**
     * Linear issue title, "" when unknown (older/adopted records)
     */
    "title": string;

    /**
     * "" when unknown
     */
    "branch": string;

    /**
     * derived (scm.DeriveStatus / hook-driven states)
     */
    "status": string;
    "prUrl": string;

    /**
     * 0 when no PR observed
     */
    "prNumber": number;

    /**
     * pass|fail|pending|none, "" when no PR
     */
    "checks": string;

    /**
     * APPROVED|CHANGES_REQUESTED|REVIEW_REQUIRED, "" otherwise
     */
    "review": string;

    /**
     * "" when no tmux session correlates
     */
    "tmuxName": string;

    /**
     * always "native"; kept for wire compat with pre-P3 clients
     */
    "source": string;

    /**
     * native runtime: the session's git worktree dir; "" otherwise
     */
    "worktree": string;

    /**
     * human duration since first observed, e.g. "2h05m"
     */
    "age": string;

    /**
     * Reaction-engine posture (PLAN P3), flattened so the TUI renders reaction
     * state without importing internal/session or re-deriving it.
     * ci_failed recovery attempts already spent on the current failing streak
     */
    "ciRetries": number;

    /**
     * ci retries exhausted; the session was handed off to a human
     */
    "escalated": boolean;

    /**
     * Reacting is a short human label of the current reaction posture, derived
     * from Status + CIRetries + Escalated: "" (nothing worth surfacing beyond
     * STATUS) | "ci retry 1/2" | "escalated" | "awaiting review" |
     * "addressing review" | "rebasing" | "ready to merge".
     */
    "reacting": string;
}

/**
 * SessionsData is Response.Data for cmd=sessions: the daemon's cached view
 * of observed agent sessions (PLAN P1). Served from the observer's snapshot
 * store — a sessions request never execs ao/gh/tmux.
 */
export interface SessionsData {
    "sessions": SessionInfo[] | null;

    /**
     * Events is the daemon's activity feed: recent notable session status
     * transitions, NEWEST FIRST, so the TUI renders a live "what's happening"
     * ticker without deriving transitions itself. Empty when nothing notable has
     * happened since the daemon started (the feed is in-memory, so it starts
     * fresh on a daemon restart but survives TUI restarts).
     */
    "events"?: Event[] | null;
}

/**
 * StatusData is Response.Data for cmd=status. RuntimeOK reports whether the
 * native runtime's external tools (tmux, git, claude) are all resolvable;
 * RuntimeErr names what is missing ("" when ok).
 */
export interface StatusData {
    "runtimeOk": boolean;
    "runtimeErr"?: string;
    "linearOk": boolean;
    "polls": PollStatus[] | null;
}

/**
 * TicketRow is one Linear issue for the picker.
 */
export interface TicketRow {
    "identifier": string;
    "uuid": string;
    "title": string;
    "branch": string;
    "priority": number;

    /**
     * a lola session already holds this issue
     */
    "alreadyLive": boolean;
}

/**
 * TicketsData is Response.Data for cmd=tickets: the browsable issues.
 */
export interface TicketsData {
    "team": string;
    "issues": TicketRow[] | null;
}
