// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CodeRabbitData is Response.Data for cmd=coderabbit: the outcome of a forced
 * PR-comment watch poll, flattened to render-ready fields for the CLI. Message is
 * the short human-readable line the CLI prints. Ran reports whether the poll ran
 * (a gh call was made); Found is true when it surfaced at least one comment;
 * Skipped names why the poll did not run (watch disabled / no open PR), ""
 * otherwise. Comments is the full, size-capped comment text (UNTRUSTED,
 * attacker-authorable) when Found — present so a caller can display it; empty on
 * none/skipped.
 */
export class CodeRabbitData {
    "ran": boolean;
    "found": boolean;
    "skipped"?: string;
    "comments"?: string;
    "message"?: string;

    /** Creates a new CodeRabbitData instance. */
    constructor($$source: Partial<CodeRabbitData> = {}) {
        if (!("ran" in $$source)) {
            this["ran"] = false;
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeRabbitData instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeRabbitData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeRabbitData($$parsedSource as Partial<CodeRabbitData>);
    }
}

/**
 * DevClashInfo is why a dev tab is dead when the reason is a port another
 * process already holds — the flattened session.DevClash, rendered by both UIs
 * beside the dev toggle.
 * 
 * It is EVIDENCE for a question, not a verdict: a client shows it and may offer
 * cmd=devFreePort, which re-checks that this pid still holds this port before
 * signalling anything. Port is the only value that came out of the terminal (an
 * integer; see internal/portclash) — Proc and Dir come from lsof, Command from
 * config.
 */
export class DevClashInfo {
    "tab": string;
    "command"?: string;
    "port": number;
    "pid": number;
    "proc"?: string;
    "dir"?: string;

    /**
     * Ours reports whether the holder is listening from inside lola's worktrees
     * for this project (a stray server of an earlier session) rather than from
     * the user's own checkout. A client should word its confirmation
     * differently for the two: reclaiming lola's own leftover is routine,
     * killing the user's process is not.
     */
    "ours"?: boolean;

    /** Creates a new DevClashInfo instance. */
    constructor($$source: Partial<DevClashInfo> = {}) {
        if (!("tab" in $$source)) {
            this["tab"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevClashInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DevClashInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevClashInfo($$parsedSource as Partial<DevClashInfo>);
    }
}

/**
 * DevData is Response.Data for cmd=dev. Active mirrors the resulting state
 * (true when tabs are running), Commands are the dev_commands the tabs run in
 * order, Stopped names the session whose tabs were taken over ("" when none
 * were), and Message is the short human-readable outcome for the CLI/TUI.
 */
export class DevData {
    "active": boolean;
    "commands"?: string[];
    "stopped"?: string;
    "message"?: string;

    /** Creates a new DevData instance. */
    constructor($$source: Partial<DevData> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevData instance from a string or object.
     */
    static createFrom($$source: any = {}): DevData {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField1_0($$parsedSource["commands"]);
        }
        return new DevData($$parsedSource as Partial<DevData>);
    }
}

/**
 * DevFreePortData is Response.Data for cmd=devFreePort. Freed reports whether
 * the holder was signalled, Dev the outcome of the restart that followed, and
 * Message the short human-readable summary for the CLI/TUI.
 */
export class DevFreePortData {
    "freed": boolean;
    "port": number;
    "dev": DevData;
    "message"?: string;

    /** Creates a new DevFreePortData instance. */
    constructor($$source: Partial<DevFreePortData> = {}) {
        if (!("freed" in $$source)) {
            this["freed"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("dev" in $$source)) {
            this["dev"] = (new DevData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevFreePortData instance from a string or object.
     */
    static createFrom($$source: any = {}): DevFreePortData {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dev" in $$parsedSource) {
            $$parsedSource["dev"] = $$createField2_0($$parsedSource["dev"]);
        }
        return new DevFreePortData($$parsedSource as Partial<DevFreePortData>);
    }
}

/**
 * Event is one session status transition surfaced in the activity feed,
 * flattened to render-ready strings so the TUI needs no scm/session imports.
 * From is the prior derived status ("" means the session was just spawned); To
 * is the new derived status; Ago is a human duration since the transition
 * (e.g. "2m", formatted daemon-side against the request time).
 */
export class Event {
    "id": string;

    /**
     * Linear identifier, e.g. ENG-123 ("" when unknown)
     */
    "issue": string;

    /**
     * Linear issue title, "" when unknown
     */
    "title"?: string;
    "from": string;
    "to": string;
    "ago": string;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("issue" in $$source)) {
            this["issue"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("ago" in $$source)) {
            this["ago"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event($$parsedSource as Partial<Event>);
    }
}

/**
 * GroupInfo is one configured [[group]] flattened for rendering. It carries no
 * live facts because a group has none — it is arrangement only, and nothing in
 * the daemon's control loop reads it.
 */
export class GroupInfo {
    "name": string;
    "label"?: string;

    /**
     * Position is the group's index among the TOP-LEVEL rows — the sidebar draws
     * folders beside the ungrouped projects, not in a section below them, so a
     * group carries its own place in that list. See config.Group.
     */
    "position": number;
    "collapsed"?: boolean;

    /** Creates a new GroupInfo instance. */
    constructor($$source: Partial<GroupInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupInfo($$parsedSource as Partial<GroupInfo>);
    }
}

/**
 * KillData is Response.Data for cmd=kill. Removed reports whether the worktree
 * was actually removed (false when the project is gone from config so there was
 * nothing safe to target, or on a dirty-refused kill — but a dirty refusal is
 * returned as an error, not a KillData). Worktree is the worktree dir the kill
 * targeted (removed or kept), "" when none applied. Message is a short
 * human-readable outcome for the CLI/TUI to print.
 */
export class KillData {
    "removed": boolean;
    "worktree"?: string;
    "message"?: string;

    /** Creates a new KillData instance. */
    constructor($$source: Partial<KillData> = {}) {
        if (!("removed" in $$source)) {
            this["removed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillData instance from a string or object.
     */
    static createFrom($$source: any = {}): KillData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillData($$parsedSource as Partial<KillData>);
    }
}

/**
 * Match describes one matched issue and what the tick did (or would do) with it.
 */
export class Match {
    "identifier": string;
    "title": string;

    /**
     * spawned|would-spawn|skipped
     */
    "action": string;

    /**
     * dedup-label|dedup-seen|in-flight|capped|error
     */
    "reason"?: string;

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * OpenData is Response.Data for cmd=open: a branch/PR manually checked out into
 * a throwaway DETACHED worktree with a plain shell (no coding agent), for running
 * and testing a PR. SessionID is the created session's ID (and its tmux target),
 * Worktree the checkout directory, Branch the human-readable label opened, and
 * Message a short human-readable outcome for the CLI/TUI to print.
 */
export class OpenData {
    "sessionId": string;
    "worktree"?: string;
    "branch"?: string;
    "message"?: string;

    /** Creates a new OpenData instance. */
    constructor($$source: Partial<OpenData> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenData instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenData($$parsedSource as Partial<OpenData>);
    }
}

/**
 * OpenManualArgs is the argument payload for cmd=openManual: create a NEW branch
 * (off Base, empty → the project's default branch) in a fresh worktree. With
 * Agent set it launches the coding agent (seeded with Prompt); otherwise a plain
 * shell. The reply is the shared OpenData.
 */
export class OpenManualArgs {
    "project": string;
    "branch": string;
    "base"?: string;

    /**
     * launch the coding agent instead of a shell
     */
    "agent"?: boolean;

    /**
     * seed prompt when Agent is set
     */
    "prompt"?: string;

    /**
     * AgentKind optionally overrides WHICH coding agent runs (claude|codex|
     * opencode) instead of the project's configured default. "" = configured.
     */
    "agentKind"?: string;

    /** Creates a new OpenManualArgs instance. */
    constructor($$source: Partial<OpenManualArgs> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenManualArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenManualArgs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenManualArgs($$parsedSource as Partial<OpenManualArgs>);
    }
}

/**
 * OpenPrArgs is the argument payload for cmd=openPr: open a PR's head branch as a
 * TRACKING worktree and launch the coding agent on it (so it can push back).
 * IsFork is set by the client for a fork PR — the daemon refuses those (no
 * push-back to a fork). The reply is the shared OpenData.
 */
export class OpenPrArgs {
    "project": string;
    "branch": string;
    "number"?: number;
    "isFork"?: boolean;

    /** Creates a new OpenPrArgs instance. */
    constructor($$source: Partial<OpenPrArgs> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenPrArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenPrArgs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenPrArgs($$parsedSource as Partial<OpenPrArgs>);
    }
}

/**
 * OpenTicketArgs is the argument payload for cmd=openTicket: start a Linear issue
 * on demand — a worktree + agent, deduped exactly like a poll dispatch so a
 * running poll cannot spawn it twice. The reply is the shared OpenData.
 */
export class OpenTicketArgs {
    "project": string;
    "identifier": string;
    "uuid": string;
    "branch"?: string;
    "title"?: string;

    /**
     * AgentKind optionally overrides WHICH coding agent runs (claude|codex|
     * opencode) instead of the project's configured default. "" = configured.
     */
    "agentKind"?: string;

    /** Creates a new OpenTicketArgs instance. */
    constructor($$source: Partial<OpenTicketArgs> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenTicketArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenTicketArgs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenTicketArgs($$parsedSource as Partial<OpenTicketArgs>);
    }
}

/**
 * PaneChoice is one enumerated option the agent offered at its prompt. Key is
 * what the human sends to select it (a menu number/letter); Label is the
 * human-readable option text.
 */
export class PaneChoice {
    "key": string;
    "label": string;

    /** Creates a new PaneChoice instance. */
    constructor($$source: Partial<PaneChoice> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaneChoice instance from a string or object.
     */
    static createFrom($$source: any = {}): PaneChoice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaneChoice($$parsedSource as Partial<PaneChoice>);
    }
}

/**
 * PaneData is Response.Data for cmd=pane (PLAN P7): the captured tmux pane text
 * plus the attention parser's read of it, flattened so the TUI renders an
 * actionable answer card without importing internal/attention (and so protocol
 * stays dependency-free). Text is the rendered pane (ANSI preserved, as
 * capture-pane -e returns it). HasQuestion reports whether a prompt was
 * detected; when true, Prompt is the question line, Choices enumerates any
 * pick-one options the agent offered (empty for a pure free-text prompt),
 * and FreeForm reports whether a typed reply is expected. Both a choice list and
 * FreeForm can be surfaced; the human either picks a Choice.Key or types text,
 * and either is delivered back via cmd=answer.
 */
export class PaneData {
    "text": string;
    "hasQuestion": boolean;
    "prompt"?: string;
    "choices"?: PaneChoice[];
    "freeForm"?: boolean;

    /** Creates a new PaneData instance. */
    constructor($$source: Partial<PaneData> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("hasQuestion" in $$source)) {
            this["hasQuestion"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaneData instance from a string or object.
     */
    static createFrom($$source: any = {}): PaneData {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("choices" in $$parsedSource) {
            $$parsedSource["choices"] = $$createField3_0($$parsedSource["choices"]);
        }
        return new PaneData($$parsedSource as Partial<PaneData>);
    }
}

/**
 * PollOnceData is Response.Data for cmd=pollOnce.
 */
export class PollOnceData {
    "poll": string;
    "dryRun": boolean;
    "matches": Match[];

    /** Creates a new PollOnceData instance. */
    constructor($$source: Partial<PollOnceData> = {}) {
        if (!("poll" in $$source)) {
            this["poll"] = "";
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollOnceData instance from a string or object.
     */
    static createFrom($$source: any = {}): PollOnceData {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField2_0($$parsedSource["matches"]);
        }
        return new PollOnceData($$parsedSource as Partial<PollOnceData>);
    }
}

export class PollStatus {
    "name": string;
    "enabled": boolean;
    "lastRun": string;
    "lastSpawn": string;

    /**
     * tick currently executing
     */
    "running": boolean;
    "lastError"?: string;

    /** Creates a new PollStatus instance. */
    constructor($$source: Partial<PollStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastSpawn" in $$source)) {
            this["lastSpawn"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PollStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PollStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PollStatus($$parsedSource as Partial<PollStatus>);
    }
}

/**
 * PrRow is one open PR for the picker.
 */
export class PrRow {
    "number": number;
    "title": string;
    "author": string;
    "branch": string;
    "isDraft": boolean;
    "isFork": boolean;

    /**
     * pass|fail|pending|none
     */
    "checks": string;
    "review": string;
    "url": string;

    /**
     * scm.DeriveStatus vocabulary
     */
    "status": string;

    /**
     * a lola session already holds this branch
     */
    "alreadyOpen": boolean;

    /** Creates a new PrRow instance. */
    constructor($$source: Partial<PrRow> = {}) {
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("isDraft" in $$source)) {
            this["isDraft"] = false;
        }
        if (!("isFork" in $$source)) {
            this["isFork"] = false;
        }
        if (!("checks" in $$source)) {
            this["checks"] = "";
        }
        if (!("review" in $$source)) {
            this["review"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("alreadyOpen" in $$source)) {
            this["alreadyOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrRow instance from a string or object.
     */
    static createFrom($$source: any = {}): PrRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrRow($$parsedSource as Partial<PrRow>);
    }
}

/**
 * ProjectInfo is one configured project flattened to render-ready fields.
 */
export class ProjectInfo {
    /**
     * Name is the project's ID — what paths, tmux names and every other
     * name-keyed protocol field use. Label is its display string, "" when the
     * project has none (render Name then).
     */
    "name": string;
    "label"?: string;

    /**
     * Group is the [[group]] Name this project is filed under, "" for the top
     * level. Always resolves to a group present in ProjectsData.Groups — config
     * repairs a dangling reference to "" on load.
     */
    "group"?: string;
    "path": string;
    "repo": string;
    "defaultBranch": string;

    /**
     * Per-PROJECT agent health (not the default agent): AgentBin is the resolved
     * coding-agent binary for this project (its override → [defaults].agent →
     * claude), AgentOK whether it plus tmux+git all resolve on PATH, AgentErr the
     * reason when not. The TUI gates this project's spawn verbs on AgentOK.
     */
    "agent": string;
    "agentBin": string;
    "agentOk": boolean;
    "agentErr"?: string;

    /**
     * PathOK is whether Path exists and is a git checkout (a .git entry); a
     * runtime probe, deliberately NOT config's job. RepoConfigured is whether a
     * GitHub "owner/name" repo is set (needed by the PR picker).
     */
    "pathOk": boolean;
    "repoConfigured": boolean;

    /**
     * Poll rollup: how many polls this project drives and how many are enabled,
     * their names, and the newest LastRun / first LastError across them.
     */
    "pollCount": number;
    "pollsEnabled": number;
    "polls"?: string[];
    "lastRun": string;
    "lastError"?: string;

    /**
     * Session rollup for this project (from the observer's snapshot store):
     * Sessions total, LiveCounted occupying a slot, NeedsYou parked on a human,
     * CIRed failing CI, OpenPRs with an open PR.
     */
    "sessions": number;
    "liveCounted": number;
    "needsYou": number;
    "ciRed": number;
    "openPrs": number;

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("defaultBranch" in $$source)) {
            this["defaultBranch"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("agentBin" in $$source)) {
            this["agentBin"] = "";
        }
        if (!("agentOk" in $$source)) {
            this["agentOk"] = false;
        }
        if (!("pathOk" in $$source)) {
            this["pathOk"] = false;
        }
        if (!("repoConfigured" in $$source)) {
            this["repoConfigured"] = false;
        }
        if (!("pollCount" in $$source)) {
            this["pollCount"] = 0;
        }
        if (!("pollsEnabled" in $$source)) {
            this["pollsEnabled"] = 0;
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = 0;
        }
        if (!("liveCounted" in $$source)) {
            this["liveCounted"] = 0;
        }
        if (!("needsYou" in $$source)) {
            this["needsYou"] = 0;
        }
        if (!("ciRed" in $$source)) {
            this["ciRed"] = 0;
        }
        if (!("openPrs" in $$source)) {
            this["openPrs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        const $$createField14_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("polls" in $$parsedSource) {
            $$parsedSource["polls"] = $$createField14_0($$parsedSource["polls"]);
        }
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * ProjectsData is Response.Data for cmd=projects: the daemon's cached view of
 * every configured [[project]] decorated with live status. Like cmd=sessions it
 * is served from in-memory snapshots (config + status tracker + session store)
 * and does not exec gh/tmux/git — the only filesystem touches are cheap
 * LookPath (agent health) and os.Stat (path/.git probe), never a subprocess. The
 * TUI renders the project list from its OWN config and merely decorates rows
 * with these facts, so the home screen stays navigable when the daemon is down.
 */
export class ProjectsData {
    "projects": ProjectInfo[];

    /**
     * Groups is the configured [[group]] table in FILE ORDER — the UI folders
     * projects are filed under. It ships beside the projects rather than being
     * derived from them because an EMPTY group is a real, renderable thing: the
     * app creates the folder first and lets projects be dragged into it after.
     */
    "groups"?: GroupInfo[];

    /** Creates a new ProjectsData instance. */
    constructor($$source: Partial<ProjectsData> = {}) {
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectsData instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectsData {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField0_0($$parsedSource["projects"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField1_0($$parsedSource["groups"]);
        }
        return new ProjectsData($$parsedSource as Partial<ProjectsData>);
    }
}

/**
 * PrsData is Response.Data for cmd=prs: the open pull requests for a project's
 * repo, flattened for the picker. Served from a short-TTL cache (the daemon
 * execs `gh pr list` on a miss); AgeSeconds/Stale let the TUI show freshness.
 */
export class PrsData {
    "repo": string;
    "prs": PrRow[];

    /**
     * how old the served snapshot is
     */
    "ageSeconds": number;

    /**
     * served past its TTL (a refresh is running/failed)
     */
    "stale": boolean;

    /** Creates a new PrsData instance. */
    constructor($$source: Partial<PrsData> = {}) {
        if (!("repo" in $$source)) {
            this["repo"] = "";
        }
        if (!("prs" in $$source)) {
            this["prs"] = [];
        }
        if (!("ageSeconds" in $$source)) {
            this["ageSeconds"] = 0;
        }
        if (!("stale" in $$source)) {
            this["stale"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrsData instance from a string or object.
     */
    static createFrom($$source: any = {}): PrsData {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prs" in $$parsedSource) {
            $$parsedSource["prs"] = $$createField1_0($$parsedSource["prs"]);
        }
        return new PrsData($$parsedSource as Partial<PrsData>);
    }
}

/**
 * RenameProjectData is Response.Data for cmd=renameProject. Message is a short
 * human-readable outcome; Blockers names the live sessions that made the daemon
 * refuse (empty on success), so the client can tell the human exactly what to
 * finish before renaming.
 */
export class RenameProjectData {
    "from": string;
    "to": string;
    "blockers"?: string[];
    "message"?: string;

    /** Creates a new RenameProjectData instance. */
    constructor($$source: Partial<RenameProjectData> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameProjectData instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameProjectData {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockers" in $$parsedSource) {
            $$parsedSource["blockers"] = $$createField2_0($$parsedSource["blockers"]);
        }
        return new RenameProjectData($$parsedSource as Partial<RenameProjectData>);
    }
}

/**
 * ResolveConflictData is Response.Data for cmd=resolveConflict. Branch is the
 * project's default_branch the agent was asked to merge (so a client can say
 * which branch it named rather than repeating its own guess), and Message is the
 * short human-readable outcome.
 */
export class ResolveConflictData {
    "branch": string;
    "message"?: string;

    /** Creates a new ResolveConflictData instance. */
    constructor($$source: Partial<ResolveConflictData> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveConflictData instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveConflictData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolveConflictData($$parsedSource as Partial<ResolveConflictData>);
    }
}

/**
 * ReviewData is Response.Data for cmd=review (PLAN P9): the outcome of a forced
 * QA review pass, flattened to render-ready fields for the CLI. Message is the
 * short human-readable line the CLI prints. Ran reports whether the review exec
 * ran; Clean is true only when it ran and found nothing; Skipped names why the
 * pass did not run (review disabled / no project), "" otherwise. Findings is the
 * full trimmed, size-capped findings text (UNTRUSTED, diff-derived) when the run
 * found issues — present so a caller can display it; empty on clean/skipped.
 */
export class ReviewData {
    "ran": boolean;
    "clean": boolean;
    "skipped"?: string;
    "findings"?: string;
    "message"?: string;

    /** Creates a new ReviewData instance. */
    constructor($$source: Partial<ReviewData> = {}) {
        if (!("ran" in $$source)) {
            this["ran"] = false;
        }
        if (!("clean" in $$source)) {
            this["clean"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviewData instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviewData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviewData($$parsedSource as Partial<ReviewData>);
    }
}

/**
 * ReviveData is Response.Data for cmd=revive: a dead session relaunched on its
 * kept worktree. Revived is always true on the success path (a failure is
 * returned as an error instead). TmuxName is the revived session's tmux target
 * and Message is a short human-readable outcome for the CLI/TUI to print.
 */
export class ReviveData {
    "revived": boolean;
    "tmuxName"?: string;
    "message"?: string;

    /** Creates a new ReviveData instance. */
    constructor($$source: Partial<ReviveData> = {}) {
        if (!("revived" in $$source)) {
            this["revived"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReviveData instance from a string or object.
     */
    static createFrom($$source: any = {}): ReviveData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReviveData($$parsedSource as Partial<ReviveData>);
    }
}

/**
 * SessionInfo is one observed session, flattened to render-ready strings and
 * ints so the TUI never needs scm/session imports or re-derivation.
 */
export class SessionInfo {
    "id": string;
    "project": string;

    /**
     * Linear identifier, e.g. ENG-123
     */
    "issue": string;

    /**
     * Linear issue title, "" when unknown (older/adopted records)
     */
    "title": string;

    /**
     * "" when unknown
     */
    "branch": string;

    /**
     * coding-agent kind driving the pane: claude|codex|opencode ("" = legacy claude)
     */
    "agent": string;

    /**
     * the rolled-up status (state.Rollup vocabulary)
     */
    "status": string;
    "prUrl": string;

    /**
     * 0 when no PR observed
     */
    "prNumber": number;

    /**
     * pass|fail|pending|none, "" when no PR
     */
    "checks": string;

    /**
     * APPROVED|CHANGES_REQUESTED|REVIEW_REQUIRED, "" otherwise
     */
    "review": string;

    /**
     * "" when no tmux session correlates
     */
    "tmuxName": string;

    /**
     * always "native"; kept for wire compat with pre-P3 clients
     */
    "source": string;

    /**
     * native runtime: the session's git worktree dir; "" otherwise
     */
    "worktree": string;

    /**
     * human duration since first observed, e.g. "2h05m"
     */
    "age": string;

    /**
     * The two state axes underneath Status (see internal/state), with raw
     * freshness timestamps so a client can render a live "ago" between
     * refreshes. All omitempty: absent on an older daemon.
     * starting|working|waiting_input|idle|exited|dead|shell|orphaned
     */
    "agentState"?: string;

    /**
     * none|draft|ci_pending|…|merged|closed
     */
    "delivery"?: string;

    /**
     * when the rolled-up Status last changed
     */
    "statusSince"?: string;

    /**
     * when the agent axis last changed
     */
    "agentStateSince"?: string;

    /**
     * last POSITIVE evidence of work
     */
    "lastActivityAt"?: string;

    /**
     * hook|pane|tmux_activity
     */
    "activitySource"?: string;

    /**
     * last successful gh PR fetch
     */
    "prObservedAt"?: string;

    /**
     * PR facts are ≥3 failed fetches old
     */
    "prStale"?: boolean;

    /**
     * agent idle at its prompt (send-keys gate open)
     */
    "atPrompt"?: boolean;

    /**
     * why waiting_input: permission_prompt|question|idle_notification|dialog
     */
    "inputReason"?: string;

    /**
     * tool the in-flight turn runs right now (PostToolUse)
     */
    "currentTool"?: string;

    /**
     * last Notification message (display-only text)
     */
    "lastNotification"?: string;

    /**
     * [statusagent] interpreter overlay — untrusted LLM text, DISPLAY ONLY,
     * pre-gated daemon-side (confidence, freshness, supersession): a client
     * renders it verbatim or not at all. InterpretedState is set ONLY when the
     * interpreter DISAGREES with agentState (render with an "approx" marker);
     * Headline ships whenever a valid judgement exists.
     * working|waiting_input|idle|stuck; "" = no override
     */
    "interpretedState"?: string;

    /**
     * one line: what the agent is doing right now
     */
    "headline"?: string;

    /**
     * what the agent needs, when blocked
     */
    "waitingOn"?: string;

    /**
     * formatted age of the judgement, e.g. "2m"
     */
    "headlineAgo"?: string;

    /**
     * Dev processes ([[project]].dev_commands). DevActive is true while this
     * session holds them — derived from live tmux facts each observe cycle, so a
     * closed tab or a crashed command reads as inactive within one cycle.
     * DevCommands is its project's configured list (in tab order, so index N-1
     * labels tab "<id>-dev-N"); a client renders the Active toggle only when it
     * is non-empty.
     * DevURLs are the local testing addresses those tabs printed
     * ("http://127.0.0.1:8001"), best first, scraped from the panes by
     * internal/devurl — lola cannot know what port the command picked, and a
     * client should offer the link rather than make a human read it out of a
     * scrolling log. Derived like DevActive: empty the moment the tabs stop.
     * Only http(s) on a loopback host ever appears here, because a client hands
     * it to an opener and pane text is untrusted.
     * DevClash is set while a dev tab of this session is dead BECAUSE another
     * process holds the port it wanted — the one dev failure lola can name and
     * offer to undo (cmd=devFreePort). nil whenever the tabs are healthy.
     */
    "devActive"?: boolean;
    "devCommands"?: string[];
    "devUrls"?: string[];
    "devClash"?: DevClashInfo | null;

    /**
     * Reaction-engine posture (PLAN P3), flattened so the TUI renders reaction
     * state without importing internal/session or re-deriving it.
     * ci_failed recovery attempts already spent on the current failing streak
     */
    "ciRetries": number;

    /**
     * ci retries exhausted; the session was handed off to a human
     */
    "escalated": boolean;

    /**
     * Reacting is a short human label of the current reaction posture, derived
     * from Status + CIRetries + Escalated: "" (nothing worth surfacing beyond
     * STATUS) | "ci retry 1/2" | "escalated" | "awaiting review" |
     * "addressing review" | "rebasing" | "ready to merge".
     */
    "reacting": string;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("issue" in $$source)) {
            this["issue"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("prUrl" in $$source)) {
            this["prUrl"] = "";
        }
        if (!("prNumber" in $$source)) {
            this["prNumber"] = 0;
        }
        if (!("checks" in $$source)) {
            this["checks"] = "";
        }
        if (!("review" in $$source)) {
            this["review"] = "";
        }
        if (!("tmuxName" in $$source)) {
            this["tmuxName"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("worktree" in $$source)) {
            this["worktree"] = "";
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }
        if (!("ciRetries" in $$source)) {
            this["ciRetries"] = 0;
        }
        if (!("escalated" in $$source)) {
            this["escalated"] = false;
        }
        if (!("reacting" in $$source)) {
            this["reacting"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        const $$createField32_0 = $$createType0;
        const $$createField33_0 = $$createType0;
        const $$createField34_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devCommands" in $$parsedSource) {
            $$parsedSource["devCommands"] = $$createField32_0($$parsedSource["devCommands"]);
        }
        if ("devUrls" in $$parsedSource) {
            $$parsedSource["devUrls"] = $$createField33_0($$parsedSource["devUrls"]);
        }
        if ("devClash" in $$parsedSource) {
            $$parsedSource["devClash"] = $$createField34_0($$parsedSource["devClash"]);
        }
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

/**
 * SessionsData is Response.Data for cmd=sessions: the daemon's cached view
 * of observed agent sessions (PLAN P1). Served from the observer's snapshot
 * store — a sessions request never execs ao/gh/tmux.
 */
export class SessionsData {
    "sessions": SessionInfo[];

    /**
     * Events is the daemon's activity feed: recent notable session status
     * transitions, NEWEST FIRST, so the TUI renders a live "what's happening"
     * ticker without deriving transitions itself. Empty when nothing notable has
     * happened since the daemon started (the feed is in-memory, so it starts
     * fresh on a daemon restart but survives TUI restarts).
     */
    "events"?: Event[];

    /** Creates a new SessionsData instance. */
    constructor($$source: Partial<SessionsData> = {}) {
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionsData instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionsData {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField1_0($$parsedSource["events"]);
        }
        return new SessionsData($$parsedSource as Partial<SessionsData>);
    }
}

/**
 * StatusData is Response.Data for cmd=status. RuntimeOK reports whether the
 * native runtime's external tools (tmux, git, claude) are all resolvable;
 * RuntimeErr names what is missing ("" when ok).
 */
export class StatusData {
    "runtimeOk": boolean;
    "runtimeErr"?: string;
    "linearOk": boolean;
    "polls": PollStatus[];

    /** Creates a new StatusData instance. */
    constructor($$source: Partial<StatusData> = {}) {
        if (!("runtimeOk" in $$source)) {
            this["runtimeOk"] = false;
        }
        if (!("linearOk" in $$source)) {
            this["linearOk"] = false;
        }
        if (!("polls" in $$source)) {
            this["polls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusData instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusData {
        const $$createField3_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("polls" in $$parsedSource) {
            $$parsedSource["polls"] = $$createField3_0($$parsedSource["polls"]);
        }
        return new StatusData($$parsedSource as Partial<StatusData>);
    }
}

/**
 * SwitchAgentArgs is the argument payload for cmd=switchAgent: replace the
 * session's coding agent with a DIFFERENT kind on the same worktree and branch
 * (SUSHI-585). Session names the target, Agent the new kind (claude|codex|
 * opencode). The old pane is stopped, a .lola/handoff.md briefing is written,
 * and the new agent launches fresh on the kept checkout. Refused for an
 * unknown session, an agentless shell, an invalid kind, the kind already
 * running, or a kind whose binary is not on PATH.
 */
export class SwitchAgentArgs {
    "session": string;
    "agent": string;

    /** Creates a new SwitchAgentArgs instance. */
    constructor($$source: Partial<SwitchAgentArgs> = {}) {
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SwitchAgentArgs instance from a string or object.
     */
    static createFrom($$source: any = {}): SwitchAgentArgs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SwitchAgentArgs($$parsedSource as Partial<SwitchAgentArgs>);
    }
}

/**
 * SwitchAgentData is Response.Data for cmd=switchAgent. Agent is the kind now
 * running; Message is the short human-readable outcome.
 */
export class SwitchAgentData {
    "agent": string;
    "message"?: string;

    /** Creates a new SwitchAgentData instance. */
    constructor($$source: Partial<SwitchAgentData> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SwitchAgentData instance from a string or object.
     */
    static createFrom($$source: any = {}): SwitchAgentData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SwitchAgentData($$parsedSource as Partial<SwitchAgentData>);
    }
}

/**
 * TicketRow is one Linear issue for the picker. Everything past Branch is
 * DISPLAY: it tells a human which issue to pick (what state it is in, who holds
 * it, how stale it is) and is never read back on the openTicket path.
 */
export class TicketRow {
    "identifier": string;
    "uuid": string;
    "title": string;
    "branch": string;
    "priority": number;

    /**
     * State is the team's own workflow-state name ("In Progress"); StateType the
     * stable enum behind it (triage|backlog|unstarted|started|completed|canceled),
     * which is what a client colours and sorts by — names are per-team text.
     */
    "state"?: string;
    "stateType"?: string;
    "assignee"?: string;
    "labels"?: string[];
    "estimate"?: number;

    /**
     * Updated is a pre-formatted age since the issue last changed ("2h05m"),
     * formatted daemon-side exactly like SessionInfo.Age so both surfaces read
     * the same and neither has to parse a timestamp.
     */
    "updated"?: string;

    /**
     * a lola session already holds this issue
     */
    "alreadyLive": boolean;

    /** Creates a new TicketRow instance. */
    constructor($$source: Partial<TicketRow> = {}) {
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("alreadyLive" in $$source)) {
            this["alreadyLive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketRow instance from a string or object.
     */
    static createFrom($$source: any = {}): TicketRow {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField8_0($$parsedSource["labels"]);
        }
        return new TicketRow($$parsedSource as Partial<TicketRow>);
    }
}

/**
 * TicketsData is Response.Data for cmd=tickets: the browsable issues. Team is
 * the UUID config keys by; TeamName/TeamKey are its resolved display identity —
 * both may be empty (the lookup fails open), so a client renders the UUID only
 * as a last resort.
 */
export class TicketsData {
    "team": string;
    "teamName"?: string;
    "teamKey"?: string;
    "issues": TicketRow[];

    /** Creates a new TicketsData instance. */
    constructor($$source: Partial<TicketsData> = {}) {
        if (!("team" in $$source)) {
            this["team"] = "";
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TicketsData instance from a string or object.
     */
    static createFrom($$source: any = {}): TicketsData {
        const $$createField3_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField3_0($$parsedSource["issues"]);
        }
        return new TicketsData($$parsedSource as Partial<TicketsData>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DevData.createFrom;
const $$createType2 = PaneChoice.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Match.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ProjectInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = GroupInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PrRow.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = DevClashInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = SessionInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = Event.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = PollStatus.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = TicketRow.createFrom;
const $$createType21 = $Create.Array($$createType20);
